start/w sas.exe -sysin dm.sas 
start/w sas.exe -sysin ae.sas  
start/w sas.exe -sysin bp.sas  
start/w sas.exe -sysin canctx.sas  
start/w sas.exe -sysin ch.sas  
start/w sas.exe -sysin cm.sas  
start/w sas.exe -sysin cmps.sas  
start/w sas.exe -sysin cmrad.sas  
start/w sas.exe -sysin cmrx.sas  
start/w sas.exe -sysin ct.sas  
start/w sas.exe -sysin death.sas  
start/w sas.exe -sysin discbtk.sas  
start/w sas.exe -sysin discepoc.sas  
start/w sas.exe -sysin dseot.sas  
start/w sas.exe -sysin dsexit.sas  
start/w sas.exe -sysin echo.sas  
start/w sas.exe -sysin ecog.sas  
start/w sas.exe -sysin eg.sas  
start/w sas.exe -sysin exbtk.sas  
start/w sas.exe -sysin excyc.sas  
start/w sas.exe -sysin exdox.sas  
start/w sas.exe -sysin exeto.sas  
start/w sas.exe -sysin exlen.sas  
start/w sas.exe -sysin expeg.sas  
start/w sas.exe -sysin expred.sas  
start/w sas.exe -sysin exrit.sas  
start/w sas.exe -sysin exvin.sas  
start/w sas.exe -sysin ie.sas  
start/w sas.exe -sysin lbbio.sas  
start/w sas.exe -sysin lbcheml.sas  
start/w sas.exe -sysin lbcoagl.sas  
start/w sas.exe -sysin lbcreatl.sas  
start/w sas.exe -sysin lbheml.sas
start/w sas.exe -sysin lbhep.sas  
start/w sas.exe -sysin lbhepa.sas  
start/w sas.exe -sysin lbpregl.sas  
start/w sas.exe -sysin lbtb.sas  
start/w sas.exe -sysin lbtshl.sas  
start/w sas.exe -sysin lburine.sas  
start/w sas.exe -sysin mh.sas  
start/w sas.exe -sysin ml.sas  
start/w sas.exe -sysin ne.sas  
start/w sas.exe -sysin nn.sas   
start/w sas.exe -sysin pe.sas  
start/w sas.exe -sysin pk.sas  
start/w sas.exe -sysin pt.sas  
start/w sas.exe -sysin recons.sas  
start/w sas.exe -sysin rs.sas  
start/w sas.exe -sysin sched.sas  
start/w sas.exe -sysin staging.sas   
start/w sas.exe -sysin survival.sas  
start/w sas.exe -sysin tb.sas  
start/w sas.exe -sysin tl.sas  
start/w sas.exe -sysin vs.sas   
