proc format;

/*****************************************************************************
 * AUTO-GENERATED FILE
 *****************************************************************************
 * Project:  ArQule ARQ 092-101 Study
 * Protocol: ARQ 092-101
 * Client:   ArQule, Inc.
 *****************************************************************************
 * Nextrials Prism(tm) Data Timestamp:             Tue, Oct  1, 2013 00:31 UTC 
 * Generated by prism2sas on:                      Tue, Oct  1, 2013 09:04 UTC 
 * Nextrials Prism(tm) 3.0.5 released on:              February 15, 2013       
 * Nextrials uses SAS v 8.2
 *****************************************************************************/


proc format;

/* arql/013/$lbco - Lab Result */
  value $lbco
    'coag_ptt' = "PTT"
    'coag_pt' = "PT"
    'coag_inr' = "INR"
  ;

/* arql/013/$lbhg - Lab Result */
  value $lbhg
    'chem_hemoglobin_a1c' = "Glycated Hemoglobin"
  ;

/* arql/013/$lbu - Lab Result */
  value $lbu
    'urine_glucose' = "Glucose"
    'urine_protein' = "Protein"
    'urine_microscopic_wbc' = "WBC"
    'urine_microscopic_rbc' = "RBC"
    'urine_specific_gravity' = "Specific Gravity"
  ;

/* arql/013/$ltchem - Chemistry Panel Lab Tests */
  value $ltchem
    'chem_triglycerides' = "Triglycerides"
    'chem_bilirubin_total' = "Total Bilirubin"
    'chem_calcium' = "Calcium"
    'chem_albumin' = "Albumin"
    'chem_bicarbonate' = "Bicarbonate"
    'chem_alt' = "ALT"
    'chem_bilirubin_total_direct' = "Direct Bilirubin"
    'chem_hdl_cholesterol' = "HDL"
    'chem_glucose' = "Glucose"
    'chem_creatinine' = "Creatinine"
    'chem_sodium' = "Sodium"
    'chem_potassium' = "Potassium"
    'chem_magnesium' = "Magnesium"
    'chem_cholesterol_total' = "Cholesterol"
    'chem_bun' = "Blood Urea Nitrogen (BUN)"
    'chem_uric_acid' = "Uric Acid"
    'chem_ldl_cholesterol' = "LDL"
    'chem_ast' = "AST"
    'chem_ldh' = "Lactate Dehydrogenase (LDH)"
    'chem_total_protein' = "Total Protein"
    'chem_phosphorus' = "Phosphorus"
    'chem_alkaline_phosphatase' = "Alkaline Phosphatase"
    'chem_chloride' = "Chloride"
  ;

/* arql/013/$ltchema - Chemistry AM4 Panel Lab Tests */
  value $ltchema
    'chem_triglycerides' = "Triglycerides"
    'chem_bilirubin_total' = "Total Bilirubin"
    'chem_calcium' = "Calcium"
    'chem_albumin' = "Albumin"
    'chem_bicarbonate' = "Bicarbonate"
    'chem_alt' = "ALT"
    'chem_bilirubin_total_direct' = "Direct Bilirubin"
    'chem_hdl_cholesterol' = "HDL"
    'chem_glucose' = "Glucose"
    'chem_sodium' = "Sodium"
    'chem_creatinine' = "Creatinine"
    'chem_potassium' = "Potassium"
    'chem_magnesium' = "Magnesium"
    'chem_cholesterol_total' = "Cholesterol"
    'chem_bun' = "Blood Urea Nitrogen (BUN)"
    'chem_uric_acid' = "Uric Acid"
    'chem_ldl_cholesterol' = "LDL"
    'chem_ast' = "AST"
    'chem_ldh' = "Lactate Dehydrogenase (LDH)"
    'chem_insulin' = "Insulin"
    'chem_total_protein' = "Total Protein"
    'chem_phosphorus' = "Phosphorus"
    'chem_alkaline_phosphatase' = "Alkaline Phosphatase"
    'chem_chloride' = "Chloride"
  ;

/* arql/013/$lthem - Hematology Panel Lab Tests */
  value $lthem
    'hem_hematocrit' = "Hematocrit"
    'hem_basophils' = "Basophils (%)"
    'hem_monocytes' = "Monocytes (%)"
    'hem_eosinophils_absolute' = "Eosinophils (Absolute)"
    'hem_lymphocytes' = "Lymphocytes (%)"
    'hem_bands_absolute' = "Bands (Absolute)"
    'hem_bands' = "Bands (%)"
    'hem_hemoglobin' = "Hemoglobin"
    'hem_wbc' = "WBC"
    'hem_neutrophils_absolute' = "Neutrophils (Absolute)"
    'hem_platelets' = "Platelets"
    'hem_rbc' = "RBC"
    'hem_neutrophils' = "Neutrophils (%)"
    'hem_basophils_absolute' = "Basophils (Absolute)"
    'hem_reticulocytes_absolute' = "Reticulocyte Count (Absolute)"
    'hem_reticulocytes' = "Reticulocyte (%)"
    'hem_monocytes_absolute' = "Monocytes (Absolute)"
    'hem_eosinophils' = "Eosinophils (%)"
    'hem_lymphocytes_absolute' = "Lymphocytes (Absolute)"
  ;

/* arql/013/$ltlbgm - Glucose Metabolism Panel Lab Tests */
  value $ltlbgm
    'chem_glucose' = "Glucose"
    'chem_insulin' = "Insulin"
  ;

/* arql/013/$map_dic - Mapping Dictionary */
  value $map_dic
    'md70' = "MedDRA 7.0"
    'WHODDxxxB September 1, 2009' = "WHODDxxxB September 1, 2009"
    'WHODDxxxB 3Q2004' = "WHODrugB 3Q2004"
    'WHODDxxxB Sept 1, 2007' = "WHODDxxxB Sept 1, 2007"
    'WHODDxxxB June 1, 2006' = "WHODDxxxB June 1, 2006"
    'WHODDxxxB 1Q2004' = "WHODrugB 1Q2004"
    'WHODDxxxC 1Q2005' = "WHODrugC 1Q2005"
    'md141' = "MedDRA 14.1"
    'md71' = "MedDRA 7.1"
    'md81' = "MedDRA 8.1"
    'md11' = "MedDRA 10.1"
    'md131' = "MedDRA 13.1"
    'WHODDxxxB 4Q2005' = "WHODrugB 4Q2005"
    'md90' = "MedDRA 9.0"
    'md120' = "MedDRA 12.0"
    'WHODDxxxB September 1, 2011' = "WHODDxxxB September 1, 2011"
    'WHODDxxxB 4Q2004' = "WHODrugB 4Q2004"
    'WHODDxxxB September 1, 2008' = "WHODDxxxB September 1, 2008"
    'WHODDxxxB June 1, 2012' = "WHODDxxxB June 1, 2012"
    'WHODDxxxC 2Q2004' = "WHODrugC 2Q2004"
    'md12' = "MedDRA 10.2"
    'WHODDxxxB 1Q2005' = "WHODrugB 1Q2005"
    'WHODDxxxB March 1, 2006' = "WHODDxxxB March 1, 2006"
    'md151' = "MedDRA 15.1"
    'WHODDxxxB December 1, 2012' = "WHODDxxxB December 1, 2012"
    'WHODDxxxC 1Q2004' = "WHODrugC 1Q2004"
    'WHODDxxxB March 1, 2008' = "WHODDxxxB March 1, 2008"
    'md10' = "MedDRA 10.0"
    'md91' = "MedDRA 9.1"
    'WHODDxxxC June 1, 2006' = "WHODDxxxC June 1, 2006"
    'md111' = "MedDRA 11.1"
    'WHODDxxxC 3Q2004' = "WHODrugC 3Q2004"
    'md60' = "MedDRA 6.0"
    'WHODDxxxB March 1, 2007' = "WHODDxxxB March 1, 2007"
    'WHODDxxxB December 1, 2006' = "WHODDxxxB December 1, 2006"
    'WHODDxxxB Dec 1, 2007' = "WHODDxxxB Dec 1, 2007"
    'WHODDxxxB 2Q2004' = "WHODrugB 2Q2004"
    'WHODDxxxC September 1, 2006' = "WHODDxxxC September 1, 2006"
    'md110' = "MedDRA 11.0"
    'md121' = "MedDRA 12.1"
    'WHODDxxxB June 1, 2007' = "WHODDxxxB June 1, 2007"
    'WHODDxxxB 1Q2006' = "WHODrugB 1Q2006"
    'md80' = "MedDRA 8.0"
    'WHODDxxxC December 1, 2006' = "WHODDxxxC December 1, 2006"
    'md51' = "MedDRA 5.1"
    'WHODDxxxC March 1, 2006' = "WHODDxxxC March 1, 2006"
    'md13' = "MedDRA 10.3"
    'WHODDxxxB June 1, 2008' = "WHODDxxxB June 1, 2008"
    'md50' = "MedDRA 5.0"
    'WHODDxxxB March 1, 2010' = "WHODDxxxB March 1, 2010"
    'WHODDxxxB September 1, 2006' = "WHODDxxxB September 1, 2006"
    'md61' = "MedDRA 6.1"
    'md140' = "MedDRA 14.0"
    'WHODDxxxB December 1, 2011' = "WHODDxxxB December 1, 2011"
    'md150' = "MedDRA 15.0"
    'WHODDxxxB December 1, 2008' = "WHODDxxxB December 1, 2008"
    'WHODDxxxB December 1, 2010' = "WHODDxxxB December 1, 2010"
  ;

/* arql/013/$map_pro - Mapping Product */
  value $map_pro
    'dsn2' = "dsNavigator 2.x"
    'dsn3' = "dsNavigator 3.x"
  ;

/* arql/013/$map_sou - dsNavigator Source */
  value $map_sou
    'S' = "Synonym match"
    '*' = "Manual encode"
    'A' = "Autoencoded"
    'X' = "Exact match"
  ;

/* arql/013/NoYes -  */
  value NoYes
    0 = "No"
    1 = "Yes"
  ;

/* arql/013/aeacn - Study Drug Action Taken */
  value aeacn
    1 = "None/Dose Not Changed"
    2 = "Discontinued Permanently"
    3 = "Reduced"
    4 = "Temporarily Interrupted"
    5 = "Temporarily Interrupted and Reduced"
    6 = "N/A (Drug Discontinued Prior to Onset of Event/Patient no on Treatment at the Time of Event)"
  ;

/* arql/013/aeactoth - Other Action Taken */
  value aeactoth
    1 = "None"
    2 = "Medication Required"
    3 = "Hospitalization"
    99 = "Other (Specify)"
  ;

/* arql/013/aecaus - Causality */
  value aecaus
    1 = "Related"
    2 = "Not Related"
  ;

/* arql/013/aenci - NCI CTCAE Grade */
  value aenci
    1 = "1"
    2 = "2"
    3 = "3"
    4 = "4"
    5 = "5"
  ;

/* arql/013/aeongo - Ongoing */
  value aeongo
    1 = "Ongoing Checked"
  ;

/* arql/013/aeout - Outcome */
  value aeout
    1 = "Recovered/Resolved"
    2 = "Resolved/ Resolved with Sequelae/Residual Effect(s) Present"
    3 = "Not Recovered/Not Resolved"
    4 = "Fatal"
    5 = "Unknown"
  ;

/* arql/013/bdbdedbf - Dose Reduction */
  value bdbdedbf
    0 = "No"
    1 = "Yes (Specify Reason)"
  ;

/* arql/013/cafcefec - Dose Held */
  value cafcefec
    0 = "No (Specify Reason)"
    1 = "Yes"
  ;

/* arql/013/cbaaacfc - Locked Flag */
  value cbaaacfc
    0 = "Unlocked"
    1 = "Locked"
  ;

/* arql/013/chbiop - Type of Biopsy or Procedure */
  value chbiop
    1 = "Fine Needle Aspiration Biopsy"
    2 = "Core Needle Biopsy"
    3 = "Excisional Biopsy"
    4 = "Brushing/Washing"
    5 = "Surgery (Specify)"
    99 = "Other (Specify)"
  ;

/* arql/013/chctype - Diagnosis Information/Cancer Types: Cancer History */
  value chctype
    1 = "Bladder"
    2 = "Breast"
    3 = "Colorectal"
    4 = "Esophageal"
    5 = "Head and Neck"
    6 = "Liver"
    7 = "Ovarian"
    8 = "NSCLC"
    9 = "Prostate"
    10 = "Renal"
    11 = "Stomach"
    12 = "Pancreatic"
    13 = "Hodgkins Lymphoma"
    14 = "Non-Hodgkins Lymphoma (transformed from CLL)"
    15 = "Non-Hodgkins Lymphoma (NOT transformed from CLL)"
    99 = "Other (Specify)"
  ;

/* arql/013/chgrade - Grade */
  value chgrade
    1 = "Well Differentiated"
    2 = "Moderately Differentiated"
    3 = "Poorly Differentiated/Undifferentiated"
    99 = "Unknown"
  ;

/* arql/013/chprim - Primary Cancer */
  value chprim
    1 = "Current Cancer"
    2 = "Previous Cancer"
  ;

/* arql/013/chstgd - Tumor Staging at Diagnosis */
  value chstgd
    1 = "0"
    2 = "I A"
    3 = "I B"
    4 = "II A"
    5 = "II B"
    6 = "III"
    7 = "IV"
    8 = "IE-A"
    9 = "IE-B"
    10 = "IIE-A"
    11 = "IIE-B"
    12 = "III-A"
    13 = "III-B"
    14 = "IIIE-A"
    15 = "IIIE-B"
    16 = "IIISE-A"
    17 = "IIISE-B"
    18 = "IV-A"
    19 = "IV-B"
    99 = "Other (Specify)"
  ;

/* arql/013/chstge - Tumor Staging at Study Entry */
  value chstge
    1 = "0"
    2 = "I A"
    3 = "I B"
    4 = "II A"
    5 = "II B"
    6 = "III"
    7 = "IV"
    8 = "N/A"
    9 = "IE-A"
    10 = "IE-B"
    11 = "IIE-A"
    12 = "IIE-B"
    13 = "III-A"
    14 = "III-B"
    15 = "IIIE-A"
    16 = "IIIE-B"
    17 = "IIISE-A"
    18 = "IIISE-B"
    19 = "IV-A"
    20 = "IV-B"
    99 = "Other (Specify)"
  ;

/* arql/013/chtype - Diagnosis Information/Cancer Types */
  value chtype
    1 = "Bladder"
    2 = "Breast"
    3 = "Colorectal"
    4 = "Esophageal"
    5 = "Head and Neck"
    6 = "Liver"
    7 = "Ovarian"
    8 = "NSCLC"
    9 = "Prostate"
    10 = "Renal"
    11 = "Stomach"
    12 = "Pancreatic"
    13 = "Hodgkins Lymphoma"
    14 = "Non-Hodgkins Lymphoma"
    99 = "Other (Specify)"
  ;

/* arql/013/cmfreq - Frequency */
  value cmfreq
    1 = "Once a Day"
    2 = "Twice a Day"
    3 = "Three Times a Day"
    4 = "Continuous IV"
    5 = "As Needed"
    6 = "Every Other Day"
    7 = "One Time Only"
    99 = "Other (Specify)"
  ;

/* arql/013/cmind - Indication */
  value cmind
    1 = "Prophylaxis (Specify)"
    2 = "Adverse Event (Specify)"
    3 = "Medical/Surgical History (Specify)"
    4 = "Lab Abnormality (Specify)"
    99 = "Other (Specify)"
  ;

/* arql/013/cmong - Ongoing */
  value cmong
    1 = "Ongoing Checked"
  ;

/* arql/013/cmroute - Route */
  value cmroute
    1 = "By Mouth"
    2 = "Inhaled"
    3 = "Subcutaneous"
    4 = "Intramuscular"
    5 = "Nasal"
    6 = "Topical"
    7 = "Intravenous"
    8 = "Transdermal"
    99 = "Other (Specify)"
  ;

/* arql/013/cmunit - Dose Unit */
  value cmunit
    1 = "Tablet"
    2 = "Capsule"
    3 = "mg/m2"
    4 = "mg/kg"
    5 = "mg"
    6 = "IU"
    7 = "gtt"
    8 = "puffs"
    9 = "units"
    10 = "ug"
    11 = "g"
    12 = "Not Applicable"
    13 = "Unknown"
    99 = "Other (Specify)"
  ;

/* arql/013/cnsntsbt - Subject Given Copy of Signed Consent */
  value cnsntsbt
    1 = "Subject Given Copy of Signed Consent Checked"
  ;

/* arql/013/cs - Clinically Significant */
  value cs
    1 = "Clinically Significant Checked"
  ;

/* arql/013/eabacdfe - Vital Signs Taken */
  value eabacdfe
    0 = "No (Specify)"
    1 = "Yes"
  ;

/* arql/013/efedaafa - Approved */
  value efedaafa
    0 = "Not Approved"
    1 = "Approved"
  ;

/* arql/013/egdurnd - ND */
  value egdurnd
    1 = "ND Checked"
  ;

/* arql/013/eghrnd - ND */
  value eghrnd
    1 = "ND Checked"
  ;

/* arql/013/egorres - Results */
  value egorres
    1 = "Normal"
    2 = "Abnormal, Not Clinically Significant"
    3 = "Clinically Significant Abnormal Findings"
  ;

/* arql/013/egprnd - ND */
  value egprnd
    1 = "ND Checked"
  ;

/* arql/013/egqtcnd - ND */
  value egqtcnd
    1 = "ND Checked"
  ;

/* arql/013/egqtnd - ND */
  value egqtnd
    1 = "ND Checked"
  ;

/* arql/013/egrrnd - ND */
  value egrrnd
    1 = "ND Checked"
  ;

/* arql/013/elefrs - Indicate Type of Screen Failure */
  value elefrs
    1 = "Inclusion"
    2 = "Exclusion"
    3 = "Withdrew Consent"
    4 = "Exceeded Screening Window"
    5 = "Death"
    6 = "Withdrawn by Investigator"
    7 = "Other (Specify)"
  ;

/* arql/013/esps - ECOG Status */
  value esps
    0 = "Grade 0 = Fully Active"
    1 = "Grade 1 = Restricted in Physical Strenuous Activity"
    2 = "Grade 2 = Ambulatory and Capable of Self-care"
    3 = "Grade 3 = Capable of Only Limited Self-care"
    4 = "Grade 4 = Completely Disabled"
    5 = "Grade 5 = Dead"
  ;

/* arql/013/ethnicty - Ethnicity */
  value ethnicty
    1 = "Hispanic or Latino"
    2 = "Not Hispanic or Latino"
  ;

/* arql/013/ethrnd - ND */
  value ethrnd
    1 = "ND Checked"
  ;

/* arql/013/ethrnd_b - ND */
  value ethrnd_b
    1 = "ND Checked"
  ;

/* arql/013/etnum - Pre Tracing Number */
  value etnum
    1 = "Tracing 1"
    2 = "Tracing 2"
    3 = "Tracing 3"
  ;

/* arql/013/etnum_b - Post Tracing Number */
  value etnum_b
    1 = "Tracing 1"
    2 = "Tracing 2"
    3 = "Tracing 3"
  ;

/* arql/013/etnumn_b - ND */
  value etnumn_b
    1 = "ND Checked"
  ;

/* arql/013/etnumnd - ND */
  value etnumnd
    1 = "ND Checked"
  ;

/* arql/013/etpr2nd - ND */
  value etpr2nd
    1 = "ND Checked"
  ;

/* arql/013/etprnd - ND */
  value etprnd
    1 = "ND Checked"
  ;

/* arql/013/etqrs2nd - ND */
  value etqrs2nd
    1 = "ND Checked"
  ;

/* arql/013/etqrsnd - ND */
  value etqrsnd
    1 = "ND Checked"
  ;

/* arql/013/etqt2nd - ND */
  value etqt2nd
    1 = "ND Checked"
  ;

/* arql/013/etqtc2nd - ND */
  value etqtc2nd
    1 = "ND Checked"
  ;

/* arql/013/etqtcnd - ND */
  value etqtcnd
    1 = "ND Checked"
  ;

/* arql/013/etqtnd - ND */
  value etqtnd
    1 = "ND Checked"
  ;

/* arql/013/etrr2nd - ND */
  value etrr2nd
    1 = "ND Checked"
  ;

/* arql/013/etrrnd - ND */
  value etrrnd
    1 = "ND Checked"
  ;

/* arql/013/fafbbadf - Continuing */
  value fafbbadf
    0 = "No (Provide End Date)"
    1 = "Yes"
  ;

/* arql/013/ffcfeeda - Action Taken */
  value ffcfeeda
    0 = "No"
    1 = "Yes (Specify)"
  ;

/* arql/013/fucontct - Contact Method */
  value fucontct
    1 = "Telephone Call"
    2 = "Clinic Visit"
    99 = "Other (Specify)"
  ;

/* arql/013/heightu - Height Unit */
  value heightu
    0 = "in"
    1 = "cm"
  ;

/* arql/013/lbcs - Clinically Significant */
  value lbcs
    1 = "Not Clinically Significant"
    2 = "Clinically Significant"
  ;

/* arql/013/lbnd - ND */
  value lbnd
    1 = "ND Checked"
  ;

/* arql/013/lbtmunk - Time Unknown */
  value lbtmunk
    1 = "Time Unknown Checked"
  ;

/* arql/013/lgbmtp - Scheduled Time */
  value lgbmtp
    1 = "Pre-dose"
    2 = "2 Hours Post Dose"
    3 = "4 Hours Post Dose"
    4 = "6 Hours Post Dose"
    5 = "10 Hours Post Dose"
    6 = "24 Hours Post Dose"
  ;

/* arql/013/lmme - Assessment Method */
  value lmme
    1 = "Conventional CT Scan"
    2 = "Spiral CT Scan"
    3 = "MRI"
    4 = "Physical Exam"
    5 = "PET Scan"
    6 = "X-ray"
    7 = "Bone Scan"
    8 = "Ultrasonography (USG)"
    9 = "Non-Contrast CT"
    10 = "Non-Contrast MRI"
    99 = "Other (Specify)"
  ;

/* arql/013/mmyfr - Frequency */
  value mmyfr
    1 = "QD"
    2 = "BID"
    3 = "QOD"
    4 = "5 of 7 Days"
    5 = "2 Weeks on, 1 Week off"
    6 = "1 Week on, 1 Week off"
    7 = "Once a Week"
    99 = "Other (Specify)"
  ;

/* arql/013/nd - ND */
  value nd
    1 = "ND Checked"
  ;

/* arql/013/ntasmt - Assessment */
  value ntasmt
    1 = "Present"
    2 = "Absent"
    3 = "New Lesion"
    4 = "Unequivocal Progression"
  ;

/* arql/013/ntmeth - Method of Assessment: NonTarget */
  value ntmeth
    1 = "Conventional CT Scan"
    2 = "Spiral CT Scan"
    3 = "MRI"
    4 = "Physical Exam"
    5 = "PET Scan"
    6 = "X-ray"
    7 = "Bone Scan"
    8 = "Ultrasonography (USG)"
    9 = "Non-Contrast CT"
    10 = "Non-Contrast MRI"
    99 = "Other (Specify)"
  ;

/* arql/013/ntnone - None Present */
  value ntnone
    1 = "None Present Checked"
  ;

/* arql/013/nyna - No, Yes, N/A */
  value nyna
    0 = "No (Specify Reason)"
    1 = "Yes"
    2 = "N/A"
  ;

/* arql/013/pbsch - Scheduled Time */
  value pbsch
    1 = "Pre-dose"
    2 = "2 Hours Post"
    3 = "6 Hours Post"
    4 = "10 Hours Post"
    5 = "24 Hours Post"
  ;

/* arql/013/pdreas - Deviation/Violation Reason */
  value pdreas
    1 = "Eligibility Criteria Violation/Deviation"
    2 = "Lab Test Not Done"
    3 = "Lab Test Not Done Within Specified Time Frame"
    4 = "Required Tumor Assessment Scan Not Done"
    5 = "Required Tumor Assessment Scan Not Done Within Specified Time Frame"
    6 = "Procedure Not Done"
    7 = "Procedure Not Done Within Specified Time Frame"
    8 = "Dosing Error"
    99 = "Other (Specify)"
  ;

/* arql/013/pdwaive - Waiver Granted */
  value pdwaive
    0 = "No"
    1 = "Yes"
    2 = "N/A"
  ;

/* arql/013/pestat - Result */
  value pestat
    1 = "Normal"
    2 = "Abnormal (Specify)"
    3 = "Not Examined"
  ;

/* arql/013/petest - Body Region or System */
  value petest
    1 = "General Appearance"
    2 = "Dermatological"
    3 = "Psychiatric"
    4 = "Head and Eyes"
    5 = "Ears, Nose, Mouth, and Throat"
    6 = "Pulmonary"
    7 = "Cardiovascular"
    8 = "Abdominal"
    9 = "Genito-Urinary"
    10 = "Lymphatic"
    11 = "Musculoskeletal/Extremities"
    12 = "Neurological"
  ;

/* arql/013/petest_b - Other System */
  value petest_b
    1 = "General Appearance"
    2 = "Dermatological"
    3 = "Psychiatric"
    4 = "Head and Eyes"
    5 = "Ears, Nose, Mouth, and Throat"
    6 = "Pulmonary"
    7 = "Cardiovascular"
    8 = "Abdominal"
    9 = "Genito-Urinary"
    10 = "Lymphatic"
    11 = "Musculoskeletal/Extremities"
    12 = "Neurological"
    99 = "Other (Specify)"
  ;

/* arql/013/pk12tmna - Not Applicable */
  value pk12tmna
    1 = "Not Applicable Checked"
  ;

/* arql/013/pktmpt - Scheduled Time */
  value pktmpt
    1 = "Pre-dose"
    2 = "1 Hour Post"
    3 = "2 Hours Post"
    4 = "4 Hours Post"
    5 = "6 Hours Post"
    6 = "8 Hours Post"
    7 = "10 Hours Post"
    8 = "12 Hours Post"
    9 = "24 Hours Post"
  ;

/* arql/013/plcudsna - NA */
  value plcudsna
    1 = "NA Checked"
  ;

/* arql/013/plsgth - Curative or Palliative */
  value plsgth
    1 = "Curative"
    2 = "Palliative"
  ;

/* arql/013/plsgtype - Diagnostic or Therapeutic */
  value plsgtype
    1 = "Diagnostic"
    2 = "Therapeutic"
  ;

/* arql/013/pltype - Type */
  value pltype
    1 = "Surgery"
    2 = "Radiation"
    99 = "Other (Specify)"
  ;

/* arql/013/plunitna - NA */
  value plunitna
    1 = "NA Checked"
  ;

/* arql/013/pregres - Pregnancy Test Results */
  value pregres
    1 = "Negative"
    2 = "Positive"
  ;

/* arql/013/psbres - Best Response */
  value psbres
    1 = "Complete Response"
    2 = "Partial Response"
    3 = "Stable Disease"
    4 = "Progressive Disease"
    5 = "Not Applicable"
  ;

/* arql/013/psintd - Intended For */
  value psintd
    1 = "Neo-adjuvant"
    2 = "Adjuvant"
    3 = "1st Line"
    4 = "2nd Line"
    5 = "3rd Line or Greater"
    99 = "Other (Specify)"
  ;

/* arql/013/pspgdtna - Not Applicable */
  value pspgdtna
    1 = "Not Applicable Checked"
  ;

/* arql/013/psunit - Dose Unit */
  value psunit
    1 = "Tablet"
    2 = "Capsule"
    3 = "mg/m2"
    4 = "mg/kg"
    5 = "mg"
    6 = "IU"
    7 = "gtt"
    8 = "puffs"
    9 = "units"
    10 = "ug"
    11 = "g"
    12 = "Not Applicable"
    13 = "Unknown"
    99 = "Other (Specify)"
  ;

/* arql/013/pvnum - Protocol Version */
  value pvnum
    1 = "Amendment 2"
    2 = "Amendment 3"
    3 = "Amendment 4"
    4 = "Amendment 5"
    5 = "Amendment 6"
  ;

/* arql/013/race - Race */
  value race
    1 = "American Indian or Alaska Native"
    2 = "Asian"
    3 = "Black or African American"
    4 = "Native Hawaiian or other Pacific Islander"
    5 = "Caucasian"
    99 = "Other (Specify)"
  ;

/* arql/013/rsnae - Adverse Event/SAE (Specify AE and add to AE CRF) */
  value rsnae
    1 = "Adverse Event/SAE (Specify AE and add to AE CRF) Checked"
  ;

/* arql/013/rsncd - Clinical Disease Progression (Specify Date) */
  value rsncd
    1 = "Clinical Disease Progression (Specify Date) Checked"
  ;

/* arql/013/rsndeth - Death (Specify Cause and Date) */
  value rsndeth
    1 = "Death (Specify Cause and Date) Checked"
  ;

/* arql/013/rsnltfu - Lost to Follow-up */
  value rsnltfu
    1 = "Lost to Follow-up Checked"
  ;

/* arql/013/rsnoth - Other (Specify) */
  value rsnoth
    1 = "Other (Specify) Checked"
  ;

/* arql/013/rsnpi - Physician Decision (Specify) */
  value rsnpi
    1 = "Physician Decision (Specify) Checked"
  ;

/* arql/013/rsnpv - Protocol Violation */
  value rsnpv
    1 = "Protocol Violation Checked"
  ;

/* arql/013/rsnreg - Termination of Study By the Sponsor, FDA, or Other
Regulatory Authorities */
  value rsnreg
    1 = "Termination of Study By the Sponsor, FDA, or Other Regulatory Authorities Checked"
  ;

/* arql/013/rsnwc - Withdrew Consent */
  value rsnwc
    1 = "Withdrew Consent Checked"
  ;

/* arql/013/rsnxray - Radiographic Disease Progression (Specify Date) */
  value rsnxray
    1 = "Radiographic Disease Progression (Specify Date) Checked"
  ;

/* arql/013/sdabate - Did Reaction Abate After Stopping */
  value sdabate
    0 = "No"
    1 = "Yes"
    2 = "N/A"
  ;

/* arql/013/sddc - NA - Drug Permanently Discontinued (Specify) */
  value sddc
    1 = "NA - Drug Permanently Discontinued (Specify) Checked"
  ;

/* arql/013/sddcrn - Reason Drug Discontinued */
  value sddcrn
    1 = "Adverse Event/SAE (Specify and add to AE form)"
    2 = "Lost to Follow-up"
    3 = "Death"
    4 = "Protocol Violation"
    5 = "Subject Withdrew Consent"
    6 = "Termination of Study By the Sponsor, FDA, or Other Regulatory Authorities"
    7 = "Radiographic Disease Progression"
    8 = "Clinical Disease Progression"
    9 = "Physician Decision (Specify)"
    99 = "Other (Specify)"
  ;

/* arql/013/sdhdrn - Dose Change Reason */
  value sdhdrn
    1 = "Adverse Event"
    2 = "Investigator Decision"
    99 = "Other"
  ;

/* arql/013/sex - Sex */
  value sex
    0 = "Female"
    1 = "Male"
  ;

/* arql/013/tbsamc - Type of Sample Collected */
  value tbsamc
    1 = "Archival"
    2 = "Fresh Biopsy"
    3 = "Bone Marrow Aspirate"
  ;

/* arql/013/tbsams - Type of Sample Shipped */
  value tbsams
    1 = "Fixed Slides"
    2 = "Tissue Block"
    3 = "Stained Slides"
    4 = "Unstained Slides"
  ;

/* arql/013/tlna - N/A */
  value tlna
    1 = "N/A Checked"
  ;

/* arql/013/tlnew - New Lesion */
  value tlnew
    1 = "New Lesion Checked"
  ;

/* arql/013/tlpet - PET Result */
  value tlpet
    1 = "Positive"
    2 = "Negative"
    3 = "Not Evaluable"
    4 = "Not Done"
    5 = "Not Assessed"
  ;

/* arql/013/tm_unit - Unit - Reported */
  value tm_unit
    1 = "ng/dL"
    2 = "ng/mL"
    3 = "U/mL"
    4 = "U/L"
    5 = "IU/L"
    6 = "IU/mL"
    7 = "MIU/ml"
    8 = "Mu/ml"
    9 = "mcg/L"
    99 = "Other (Specify)"
  ;

/* arql/013/tmtest - Tumor Markers Lab Tests */
  value tmtest
    1 = "CEA"
    2 = "PSA"
    3 = "aFP"
    4 = "CA27.29"
    5 = "CA19.9"
    6 = "CA15.3"
    7 = "CA125"
    8 = "bHCG"
    99 = "Other (Specify)"
  ;

/* arql/013/ttloc - Location */
  value ttloc
    1 = "Abdomen"
    2 = "Adrenal Gland - Left"
    3 = "Adrenal Gland - Right"
    4 = "Biliary Tract"
    5 = "Bladder (Urinary)"
    6 = "Brain"
    7 = "Breast - Left"
    8 = "Breast - Right"
    9 = "Cervix"
    10 = "Chest Wall"
    11 = "Colon - Ascending"
    12 = "Colon - Sigmoid"
    13 = "Colon - Transverse"
    14 = "Esophagus"
    15 = "Fallopian Tubes"
    16 = "Gallbladder"
    17 = "Head and Neck"
    18 = "Heart"
    19 = "Kidney - Left"
    20 = "Kidney - Right"
    21 = "Liver"
    22 = "Lung LLL"
    23 = "Lung LML"
    24 = "Lung LUL"
    25 = "Lung RLL"
    26 = "Lung RML"
    27 = "Lung RUL"
    28 = "Lymph Node(s) (Specify)"
    29 = "Mediastinum"
    30 = "Muscle"
    31 = "Oral"
    32 = "Ovary - Left"
    33 = "Ovary - Right"
    34 = "Pancreas - Head"
    35 = "Pancreas - Body"
    36 = "Peritoneum"
    37 = "Pleura"
    38 = "Prostate"
    39 = "Rectum"
    40 = "Skin"
    41 = "Spleen"
    42 = "Testis - Left"
    43 = "Testis - Right"
    44 = "Uterus"
    99 = "Other (Specify)"
  ;

/* arql/013/ttvis - Type of Visit */
  value ttvis
    1 = "Pre-Study"
    2 = "Week 8"
    3 = "Week 16"
    4 = "Week 24"
    5 = "Week 32"
    6 = "Week 40"
    7 = "Week 48"
    8 = "End of Study"
    99 = "Unscheduled (Specify)"
  ;

/* arql/013/tuall - Overall Response */
  value tuall
    0 = "Complete Response (CR)"
    1 = "Partial Response (PR)"
    2 = "Stable Disease (SD)"
    3 = "Progressive Disease (PD)"
    4 = "In-evaluable (NE)"
    5 = "Unknown (UNK)"
  ;

/* arql/013/tulbm - Bone Marrow */
  value tulbm
    1 = "Cleared"
    2 = "Irrelevant"
    3 = "New or Recurrent Involvement"
    4 = "Indeterminate"
    99 = "Other (Specify)"
  ;

/* arql/013/tulls - Liver and Spleen */
  value tulls
    1 = "Not Palpable"
    2 = "Nodules Disappeared"
    3 = "Greater than or equal to 50% decrease in SPD of nodules (for single nodule in greatest transverse diameter)"
    4 = "No increase in size of liver or spleen"
    5 = "Greater than 50% decrease in nadir in the SPD of any previous lesions"
    99 = "Other (Specify)"
  ;

/* arql/013/tulna - N/A */
  value tulna
    1 = "N/A Checked"
  ;

/* arql/013/tulnodal - Nodal Mass */
  value tulnodal
    1 = "PET negative, mass of any size"
    2 = "All nodal masses greater than 1.5 cm in greatest transverse diameter (GTD) at baseline are regressed to less than 1.5 cm in GTD and all nodal masses greater than 1 cm and less than 1.5 cm in GTD and g"
    3 = "All nodal masses greater than 1.5 cm in greatest transverse diameter (GTD) at baseline are regressed to less than 1.5 cm in GTD and all nodal masses greater than 1 cm and less than 1.5 cm in GTD and g"
    4 = "Greater than or equal to 50% decrease in the sum of the product of the diameters (SPD) of up to six dominant lesions identified at baseline. No new lesion"
    5 = "Greater than or equal to 50% decrease in the sum of the product of the diameters (SPD) of up to six dominant lesions identified at baseline. New lesion"
    6 = "One or more PET positive at previously involved site. No new lesion"
    7 = "One or more PET positive at previously involved site. New lesion"
    8 = "No change in size of previous lesions. No new lesion"
    9 = "No change in size of previous lesions. New lesion"
    10 = "PET positive"
    11 = "Greater than or equal to 50% increase in the SPD of target measurable nodal lesions over the smallest sum observed (over baseline if no decrease during therapy), or greater than or equal to 50% increa"
    12 = "Greater than or equal to 50% increase in the SPD of target measurable nodal lesions over the smallest sum observed (over baseline if no decrease during therapy), or greater than or equal to 50% increa"
    13 = "Unknown"
    14 = "Not All Evaluated"
    99 = "Other (Specify)"
  ;

/* arql/013/tuloall - Overall Assessment */
  value tuloall
    1 = "CR - Complete Remission"
    2 = "PR - Partial Response"
    3 = "SD - Stable Disease"
    4 = "PD - Progressive Disease"
    5 = "RD - Relapsed Disease"
  ;

/* arql/013/tuntrg - Non-Target Lesions */
  value tuntrg
    0 = "Complete Response (CR)"
    1 = "Non-Complete Response/Non-Progressive Disease"
    2 = "Progressive Disease (PD)"
    3 = "Unknown (UNK)"
    4 = "Not All Evaluated"
  ;

/* arql/013/tutrg - Target Lesions */
  value tutrg
    0 = "Complete Response (CR)"
    1 = "Partial Response (PR)"
    2 = "Stable Disease (SD)"
    3 = "Progressive Disease (PD)"
    4 = "Unknown (UNK)"
    5 = "Not All Evaluated"
  ;

/* arql/013/unlabc - Chemistry */
  value unlabc
    1 = "Chemistry Checked"
  ;

/* arql/013/unlabcg - Coagulation */
  value unlabcg
    1 = "Coagulation Checked"
  ;

/* arql/013/unlabgh - Glycated Hemoglobin */
  value unlabgh
    1 = "Glycated Hemoglobin Checked"
  ;

/* arql/013/unlabh - Hematology */
  value unlabh
    1 = "Hematology Checked"
  ;

/* arql/013/unlabua - Urinalysis */
  value unlabua
    1 = "Urinalysis Checked"
  ;

/* arql/013/unmuga - MUGA/Echocardiogram */
  value unmuga
    1 = "MUGA/Echocardiogram Checked"
  ;

/* arql/013/unsecg - ECG */
  value unsecg
    1 = "ECG Checked"
  ;

/* arql/013/unsecog - ECOG */
  value unsecog
    1 = "ECOG Checked"
  ;

/* arql/013/unspe - Physical Examination */
  value unspe
    1 = "Physical Examination Checked"
  ;

/* arql/013/unstumor - Tumor Marker */
  value unstumor
    1 = "Tumor Marker Checked"
  ;

/* arql/013/unsvs - Vital Sign */
  value unsvs
    1 = "Vital Sign Checked"
  ;

/* arql/013/vsbpnd - ND */
  value vsbpnd
    1 = "ND Checked"
  ;

/* arql/013/vshrnd - ND */
  value vshrnd
    1 = "ND Checked"
  ;

/* arql/013/vsrespnd - ND */
  value vsrespnd
    1 = "ND Checked"
  ;

/* arql/013/vstempnd - ND */
  value vstempnd
    1 = "ND Checked"
  ;

/* arql/013/vstu - Temperature Unit */
  value vstu
    1 = "Fahrenheit"
    2 = "Celsius"
  ;

/* arql/013/vswtnd - ND */
  value vswtnd
    1 = "ND Checked"
  ;

/* arql/013/vswtu - Weight Unit */
  value vswtu
    1 = "lb"
    2 = "kg"
  ;

   value $VISIT
        '1' = 'Pre-Study'
        '2' = 'Week 8'
        '3' = 'Week 16'
        '4' = 'Week 24'
        '5' = 'Week 32'
        '6' = 'Week 40'
        '7' = 'Week 48'
        '8' = 'End of Study'
        '99' = 'Unscheduled' 
      'Pre-Study Visit' = 'Pre-Study'
      'Pre-Study' = 'Pre-Study'
      'Week 1 (Day 1)' = 'Week 1 (Day 1)'
      'Week 1' = 'Week 1 (Day 1)'
      'Week 2 (Day 8)' = 'Week 2 (Day 8)'
      'Week 2' = 'Week 2 (Day 8)'
      'Week 3 (Day 15)' = 'Week 3 (Day 15)'
      'Week 3' = 'Week 3 (Day 15)'
      'Week 4 (Day 22)' = 'Week 4 (Day 22)'
      'Week 4' = 'Week 4 (Day 22)'
      'Week 5 (Day 29)' = 'Week 5 (Day 29)'
      'Week 5' = 'Week 5 (Day 29)' 
      'Week 6' = 'Week 6'
      'Week #07' = 'Week 7'
      'Week 7' = 'Week 7'
      'Week 8' = 'Week 8'
      'Week #09' = 'Week 9'
      'Week 9' = 'Week 9'
      'Week #11' = 'Week 11'
      'Week 11' = 'Week 11'
      'Week #13' = 'Week 13'
      'Week 13' = 'Week 13'
      'Week 14' = 'Week 14'
      'Week #15' = 'Week 15'
      'Week 15' = 'Week 15'
      'Week 16' = 'Week 16'
      'Week #17' = 'Week 17'
      'Week 17' = 'Week 17'
      'Week #19' = 'Week 19'
      'Week 19' = 'Week 19'
      'Week #21' = 'Week 21'
      'Week 21' = 'Week 21'
      'Week #23' = 'Week 23'
      'Week 23' = 'Week 23'
      'Week 24' = 'Week 24'
        'Week 25' = 'Week 25'
        'Week #25' = 'Week 25'
        'Week 27' = 'Week 27'
        'Week 29' = 'Week 29'
        'Week 31' = 'Week 31'
        'Week #27' = 'Week 27'
        'Week #29' = 'Week 29'
        'Week #31' = 'Week 31'
      'Week 32' = 'Week 32'
      'Week 33' = 'Week 33'
        'Week #33' = 'Week 33'
        'Week #35' = 'Week 35'
        'Week 35' = 'Week 35'
        'Week #37' = 'Week 37'
        'Week 37' = 'Week 37'
        'Week #39' = 'Week 39'
        'Week 39' = 'Week 39'
      'Week 40' = 'Week 40'
        'Week #41' = 'Week 41'
        'Week 41' = 'Week 41'
        'Week #43' = 'Week 43'
      'Week 43' = 'Week 43'
        'Week #45' = 'Week 45'
        'Week 45' = 'Week 45'
        'Week 47' = 'Week 47'
        'Week #47' = 'Week 47'
      'Week 48' = 'Week 48'
      'Week #49' = 'Week 49'
      'Week 49' = 'Week 49'
      'Week #51' = 'Week 51'
      'Week 51' = 'Week 51'
      'Week #53' = 'Week 53'
      'Week 53' = 'Week 53'
      'Week #55' = 'Week 55'
      'Week 55' = 'Week 55'
      'Week #57' = 'Week 57'
      'Week 57' = 'Week 57'
      'Week #59' = 'Week 59'
      'Week 59' = 'Week 59'
      'Week #61' = 'Week 61'
      'Week 61' = 'Week 61'
      'Week #63' = 'Week 63'
      'Week 63' = 'Week 63'
      'Week 4 (Day 21 and 22)' = 'Week 4 (Day 21 and 22)' 
      'Unscheduled Visit #01' = 'Unscheduled Visit #01'
      'Unscheduled Visit #02' = 'Unscheduled Visit #02'
        'Unscheduled Visit #03' = 'Unscheduled Visit #03'
        'Unscheduled Visit #04' = 'Unscheduled Visit #04'
      'Unscheduled Visit #05' = 'Unscheduled Visit #05'
      'Unscheduled Visit #06' = 'Unscheduled Visit #06'
      'Unscheduled Visit #07' = 'Unscheduled Visit #07'
      'Unscheduled Visit #08' = 'Unscheduled Visit #08'
      'Unscheduled (Specify)' = 'Unscheduled (Specify)'
      'End of Treatment' = 'End of Treatment'
      'End of Study' = 'End of Treatment'
      '30 Day Safety Follow-up' = '30 Day Safety Follow-up'
      'C1D1_PRE' = 'Cycle 1 Day 1'
      'C1D1_2'  = 'Cycle 1 Day 1'
      'C1D1_6' = 'Cycle 1 Day 1'
      'C1D1_10' = 'Cycle 1 Day 1'
      'C1D1_POST' = 'Cycle 1 Day 1'
      'C1D15_PRE' = 'Cycle 1 Day 15'
      'C1D15_2' = 'Cycle 1 Day 15'
      'C1D15_6' = 'Cycle 1 Day 15'
      'C1D15_10' = 'Cycle 1 Day 15'
      'C1D15_POST' = 'Cycle 1 Day 15'
   ;


   value $VNUM
        '1' = '0'
        '2' = '8'
        '3' = '16'
        '4' = '24'
        '5' = '32'
        '6' = '40'
        '7' = '48'
        '8' = '97'
        '99' = '99' 
      'Pre-Study Visit' = '0'
      'Pre-Study' = '0'
      'Week 1 (Day 1)' = '1'
      'Week 1' = '1'
      'Week 2 (Day 8)' = '2'
      'Week 2' = '2'
      'Week 3 (Day 15)' = '3'
      'Week 3' = '3'
      'Week 4 (Day 22)' = '4'
      'Week 4' = '4'
      'Week 4 (Day 21 and 22)' = '4.5'
      'Week 5 (Day 29)' = '5'      
      'Week 5' = '5'
      'Week 6' = '6'
      'Week #07' = '7'
      'Week 7' = '7'
      'Week 8' = '8'
      'Week #09' = '9'
      'Week 9' = '9'
      'Week #11' = '11'
      'Week 11' = '11'
      'Week #13' = '13'
      'Week 13' = '13'
      'Week 14' = '14'
      'Week #15' = '15'
      'Week 15' = '15'
      'Week 16' = '16'
      'Week #17' = '17'
      'Week 17' = '17'
      'Week 19' = '19'
      'Week #19' = '19'
      'Week #21' = '21'
      'Week 21' = '21'
      'Week #23' = '23'
      'Week 23' = '23'
      'Week 24' = '24'
      'Week 25' = '25'
        'Week #25' = '25'
        'Week 27' = '27'
        'Week 29' = '29'
        'Week 31' = '31'
        'Week #27' = '27'
        'Week #29' = '29'
        'Week #31' = '31'
      'Week 32' = '32'
      'Week 33' = '33'
        'Week #33' = '33'
        'Week #35' = '35'
        'Week 35' = '35'
        'Week #37' = '37'
        'Week 37' = '37'
      'Week 40' = '40'
        'Week #39' = '39'
        'Week 39' = '39'
        'Week #41' = '41'
        'Week 41' = '41'
        'Week #43' = '43'
        'Week 43' = '43'
        'Week #45' = '45'
        'Week 45' = '45'
        'Week 47' = '47'
        'Week #47' = '47'
      'Week 48' = '48'
      'Week #49' = '49'
      'Week 49' = '49'
      'Week #51' = '51'
      'Week 51' = '51'
      'Week #53' = '53'
      'Week 53' = '53'
      'Week #55' = '55'
      'Week 55' = '55'
      'Week #57' = '57'
      'Week 57' = '57'
      'Week #59' = '59'
      'Week 59' = '59'
      'Week #61' = '61'
      'Week 61' = '61'
      'Week #63' = '63'
      'Week 63' = '63'
      'Unscheduled Visit #01' = '99.01'
        'Unscheduled Visit #02' = '99.02'
        'Unscheduled Visit #03' = '99.03'
        'Unscheduled Visit #04' = '99.04'
      'Unscheduled Visit #05' = '99.05'
      'Unscheduled Visit #06' = '99.06'
      'Unscheduled Visit #07' = '99.07'
      'Unscheduled Visit #08' = '99.08'
      'Unscheduled Visit #09' = '99.09'
      'Unscheduled Visit #10' = '99.10'
      'Unscheduled Visit #11' = '99.11'
      'Unscheduled Visit #12' = '99.12'
      'Unscheduled Visit #13' = '99.13'
      'Unscheduled Visit #14' = '99.14'
      'Unscheduled Visit #15' = '99.15'
      'Unscheduled Visit #16' = '99.16'
      'Unscheduled Visit #17' = '99.17'
      'Unscheduled Visit #18' = '99.18'
      'Unscheduled Visit #19' = '99.19'
      'Unscheduled Visit #20' = '99.20'
      'Unscheduled (Specify)' = '99'
      'End of Treatment' = '97'
      'End of Study' = '97'
      '30 Day Safety Follow-up' = '100.030'
      'C1D1_PRE' = '1.01'
      'C1D1_2'  = '1.01'
      'C1D1_6' = '1.01'
      'C1D1_10' = '1.01'
      'C1D1_POST' = '1.01'
      'C1D15_PRE' = '1.15'
      'C1D15_2' = '1.15'
      'C1D15_6' = '1.15'
      'C1D15_10' = '1.15'
      'C1D15_POST' = '1.15'
    'Food Effect W2D8 #01' = '2'
;

value loc
    1 = 'Abdomen'
    2 = 'Adrenal Gland - Left'
    3 = 'Adrenal Gland - Right'
    4 = 'Biliary Tract'
    5 = 'Bladder (Urinary)'
    6 = 'Brain'
    7 = 'Breast - Left'
    8 = 'Breast - Right'
    9 = 'Cervix'
    10 = 'Chest Wall'
    11 = 'Colon - Ascending'
    12 = 'Colon - Sigmoid'
    13 = 'Colon - Transverse'
    14 = 'Esophagus'
    15 = 'Fallopian Tubes'
    16 = 'Gallbladder'
    17 = 'Head and Neck'
    18 = 'Heart'
    19 = 'Kidney - Left'
    20 = 'Kidney - Right'
    21 = 'Liver'
    22 = 'Lung LLL'
    23 = 'Lung LML'
    24 = 'Lung LUL'
    25 = 'Lung RLL'
    26 = 'Lung RML'
    27 = 'Lung RUL'
    28 = 'Lymph Node(s)'
    29 = 'Mediastinum'
    30 = 'Muscle'
    31 = 'Oral'
    32 = 'Ovary - Left'
    33 = 'Ovary - Right'
    34 = 'Pancreas - Head'
    35 = 'Pancreas - Body'
    36 = 'Peritoneum'
    37 = 'Pleura'
    38 = 'Prostate'
    39 = 'Rectum'
    40 = 'Skin'
    41 = 'Spleen'
    42 = 'Testis -Left'
    43 = 'Testis - Right'
    44 = 'Uterus'
    99 = 'Other'
    ;

    value tutrg
    0 = 'Complete Response (CR)'
    1 = 'Partial Response (PR)'
    2 = 'Stable Disease (SD)'
    3 = 'Progressive Disease(PD)'
    4 = 'Unknown (UNK)'
    5 = 'Not All Evaluated'
    ;

    value tuntrg
    0 = 'Complete Response (CR)'
    1 = 'Non-Complete Response/Non-Progressive Disease'
    2 = 'Progressive Disease (PD)'
    3 = 'Unknown (UNK)'
    4 = 'Not All Evaluated'
    ;

    value tuall
    0 = 'Complete Response (CR)'
    1 = 'Partial Response (PR)'
    2 = 'Stable Disease (SD)'
    3 = 'Progressive Disease (PD)'
    4 = 'In-evaluable (NE)'
    5 = 'Unknown (UNK)'
    ;

value method
1 = 'Conventional CT Scan'
2 = 'Spiral CT Scan'
3 = 'MRI'
4 = 'Physical Exam'
5 = 'PET Scan'
6 = 'X-ray'
7 = 'Bone Scan'
8 = 'Ultrasonography (USG)'
9 = 'Non-Contrast CT'
10 = 'Non-Contrast MRI'
99 = 'Other'
;
value tlmod
1= 'Spiral CT'
2= 'Conventional CT'
3= 'MRI'
4= 'PET'
5= 'CT Guided PET Scan'
99= 'Other'
;

value tlpet
1 = 'Not Done' 
2 = 'Positive'
3 = 'Negative'
4 = 'No change from first on-study PET scan'
5 = 'Increased from first on-study scan'
6 = 'Decreased from first on-study scan'
99= 'Other'
;

    value cmind
    1 = 'Prophylaxis'
    2 = 'Adverse Event'
    3 = 'Medical/Surgical History'
    4 = 'Lab Abnormality'
    99 = 'Other'
    ;

    value cmunit
    1 = 'Tablet'
    2 = 'Capsule'
    3 = 'mg/m2'
    4 = 'mg/kg'
    5 = 'mg'
    6 = 'IU'
    7 = 'gtt'
    8 = 'puffs'
    9 = 'units'
    10 = 'ug'
    11 = 'g'
    12 = 'Not Applicable'
    13 = 'Unknown'
    99 = 'Other'
    ;

    value cmfreq
    1 = 'Once a Day'
    2 = 'Twice a Day'
    3 = 'Three Times a Day'
    4 = 'Continuous IV'
    5 = 'As Needed'
    6 = 'Every Other Day'
    7 = 'One Time Only'
    99 = 'Other'
    ;

    value cmroute
    1 = 'By Mouth'
    2 = 'Inhaled' 
    3 = 'Subcutaneous' 
    4 = 'Intramuscular' 
    5 = 'Nasal'
    6 = 'Topical'
    7 = 'Intravenous'
    8 = 'Transdermal' 
    99 = 'Other'
    ;

    value response
    1= 'CR'
    2= 'PR'
    3= 'SD'
    4= 'Relapsed Disease or PD'
    5= 'Not Done'
    6= 'Not Applicable (Not Involved at Baseline)'
    99 = 'Other'
    ;

    value tulmd
    0 = 'No'
    1 = 'Yes '
    2 = 'Not Applicable'
    99 = 'Other'
    ;

    value tulns
    0 = No
    1 = Yes
    99=Other
    ;

    value tuloall
    1 = 'CR - Complete Remission'
    2 = 'PR - Partial Response'
    3 = 'SD - Stable Disease'
    4 = 'PD or RD - Progressive Disease or Relapsed Disease'
    5 = 'Not Evaluable'
    99 = 'Other'
    ;

run;

 /* EOF */
