start /w sas.exe -sysin AE.sas
start /w sas.exe -sysin CM.sas
start /w sas.exe -sysin CM01.sas
start /w sas.exe -sysin CM02.sas
start /w sas.exe -sysin DM.sas
start /w sas.exe -sysin DIS.sas
start /w sas.exe -sysin ECOG.sas
start /w sas.exe -sysin EX.sas
start /w sas.exe -sysin EXDIS.sas
start /w sas.exe -sysin MH.sas
start /w sas.exe -sysin MH01.sas
start /w sas.exe -sysin MH02.sas
start /w sas.exe -sysin TUT.sas
start /w sas.exe -sysin TUNT.sas
start /w sas.exe -sysin RS.sas
start /w sas.exe -sysin TULYM.sas
start /w sas.exe -sysin RSLYM.sas
start /w sas.exe -sysin SFU.sas
start /w sas.exe -sysin HEMA.sas
start /w sas.exe -sysin LBCOAG.sas
start /w sas.exe -sysin CHEM.sas
start /w sas.exe -sysin LBURIN.sas
start /w sas.exe -sysin GLUCOSE.sas
start /w sas.exe -sysin EXTRA01.sas
start /w sas.exe -sysin EXTRA02.sas
start /w sas.exe -sysin EXTRA03.sas
start /w sas.exe -sysin EXTRA04.sas
start /w sas.exe -sysin pd.sas
start /w sas.exe -sysin el.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin eg.sas
rem start /w sas.exe -sysin preecg.sas
rem start /w sas.exe -sysin pstecg.sas
start /w sas.exe -sysin preg.sas
start /w sas.exe -sysin me.sas