start/w sas.exe -sysin DM.sas
start/w sas.exe -sysin AE.sas
start/w sas.exe -sysin CH.sas
start/w sas.exe -sysin CM.sas
start/w sas.exe -sysin CPS.sas
start/w sas.exe -sysin SD.sas
start/w sas.exe -sysin LBC.sas
start/w sas.exe -sysin LBCOAG.sas
start/w sas.exe -sysin LBH.sas
start/w sas.exe -sysin MH1.sas
start/w sas.exe -sysin MH2.sas
start/w sas.exe -sysin pcs.sas
start/w sas.exe -sysin pr.sas
start/w sas.exe -sysin ps.sas