start /w sas.exe -sysin rfstdtc.sas
start /w sas.exe -sysin dm.sas
start /w sas.exe -sysin ae.sas
start /w sas.exe -sysin am.sas
start /w sas.exe -sysin bp.sas
start /w sas.exe -sysin ch.sas
start /w sas.exe -sysin cm.sas
start /w sas.exe -sysin cmrad.sas
start /w sas.exe -sysin cmrx.sas
start /w sas.exe -sysin cr.sas
start /w sas.exe -sysin ct.sas
start /w sas.exe -sysin ds.sas
start /w sas.exe -sysin disc.sas
start /w sas.exe -sysin dlt.sas
start /w sas.exe -sysin dseot.sas
start /w sas.exe -sysin ecog.sas
start /w sas.exe -sysin eg.sas
start /w sas.exe -sysin ex.sas
start /w sas.exe -sysin exbtk.sas
start /w sas.exe -sysin exlen.sas
start /w sas.exe -sysin exrit.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin lb.sas
start /w sas.exe -sysin qlab.sas
start /w sas.exe -sysin mh.sas
start /w sas.exe -sysin ne.sas
start /w sas.exe -sysin nn.sas
start /w sas.exe -sysin pe.sas
start /w sas.exe -sysin pk.sas
start /w sas.exe -sysin pt.sas
start /w sas.exe -sysin rs.sas
start /w sas.exe -sysin staging.sas
start /w sas.exe -sysin tl.sas
start /w sas.exe -sysin vs.sas
start /w sas.exe -sysin enroll.sas
start /w sas.exe -sysin fu.sas
start /w sas.exe -sysin ps.sas
start /w sas.exe -sysin pdsuspec.sas
start /w sas.exe -sysin tb.sas
start /w sas.exe -sysin tx.sas
start /w sas.exe -sysin sched.sas
start /w sas.exe -sysin surghx.sas
start /w sas.exe -sysin visit.sas
start /w sas.exe -sysin up.sas