start /w sas.exe -sysin dm.sas
start /w sas.exe -sysin end.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin mh.sas
start /w sas.exe -sysin da.sas
start /w sas.exe -sysin fast.sas
start /w sas.exe -sysin admin.sas
start /w sas.exe -sysin pk.sas
start /w sas.exe -sysin ae.sas
start /w sas.exe -sysin cm.sas
start /w sas.exe -sysin vs.sas
start /w sas.exe -sysin ecg.sas
start /w sas.exe -sysin pe.sas
start /w sas.exe -sysin ecog.sas
start /w sas.exe -sysin preg.sas
start /w sas.exe -sysin tu.sas
start /w sas.exe -sysin lb.sas