%include '_setup.sas';

*<FA----------------------------------------------------------------------------------------;
data fa0;
	length FLAG $40;
	set source.RD_FRMNSCLCHX;
	%adjustvalue(dsetlabel=NSCLC History);
	%informatDate(DOV);
	%formatDate(ITMNSCLCHXDIADT_DTS);
	label
		A_DOV='Visit Date'
		FASTDTC='Date of diagnosis'
		SITE='Sites of metastases'
		OVSTG='Overall stage'
		NSCLCT='T'
		NSCLCN='N'
		NSCLCM='M'
        FLAG='Form Name'  
	;
	FASTDTC=ITMNSCLCHXDIADT_DTS;
	OVSTG=ITMNSCLCHXOVSTG;
	NSCLCT=ITMNSCLCHXOVSTGT;
	NSCLCN=ITMNSCLCHXOVSTGN;
	NSCLCM=ITMNSCLCHXOVSTGM;
	ITMNSCLCHXMT_OTH=propcase(ITMNSCLCHXMT_ITMNSCLCHXMO_C);
	%concatoth(var=ITMNSCLCHXMT_OTH,oth=ITMNSCLCHXMO,newvar=OTHER);
	SITE=catx(', ',ITMNSCLCHXMT_CITMNONE, ITMNSCLCHXMT_CITMCNS, ITMNSCLCHXMT_CITMBONESPN, ITMNSCLCHXMT_CITMSKIN, ITMNSCLCHXMT_CITMLUNG, 
				ITMNSCLCHXMT_CITMLIVER, ITMNSCLCHXMT_CITMSPLEEN, ITMNSCLCHXMT_CITMLYMNODES, ITMNSCLCHXMT_CITMCHSTWALL, ITMNSCLCHXMT_CITMESOPHAG, 
				ITMNSCLCHXMT_CITMSTOMACH, ITMNSCLCHXMT_CITMBREAST, ITMNSCLCHXMT_CITMOVARY, ITMNSCLCHXMT_CITMPANCREAS, ITMNSCLCHXMT_CITMADKIDNEY, 
				ITMNSCLCHXMT_CITMCOLON,ITMNSCLCHXMT_CITMRECTAL,OTHER);

	FLAG='NSCLC History';
	keep &GlobalVars1 FLAG FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;

run;
data fa08;
	retain &GlobalVars1 FLAG FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	keep &GlobalVars1 FLAG FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	set fa0;
run; 


data fa20;
	length FLAG $40;
	set source.RD_FRMNSCLC;
	%adjustvalue(dsetlabel=NSCLC History);
	%informatDate(DOV);
	%formatDate(ITMNSCLCSTAGINGDT_DTS);
	label
		A_DOV='Visit Date'
		HISTOLOGY='Histology'
		FASTDTC='Date of diagnosis'
		SITE='Sites of metastases'
		OVSTG='Overall stage'
		NSCLCT='T'
		NSCLCN='N'
		NSCLCM='M'
		FLAG='Form Name' 
	;
	FASTDTC=ITMNSCLCSTAGINGDT_DTS;
	OVSTG=ITMNSCLCOVSTG;
	NSCLCT=ITMNSCLCAJCCT;
	NSCLCN=ITMNSCLCAJCCN;
	NSCLCM=ITMNSCLCAJCCM;

	ITMNSCLCHSTOT_C=propcase(ITMNSCLCHST_ITMNSCLCHSTOT_C);
	%concatoth(var=ITMNSCLCHSTOT_C,oth=ITMNSCLCHSTOT,newvar=OTHER);
	HISTOLOGY=catx(', ',ITMNSCLCHST_CITMSQUAMOUS, ITMNSCLCHST_CITMADENOCARC, ITMNSCLCHST_CITMLARGECELL, OTHER); 
	ITMNSCLCHXMT_OTH=propcase(ITMNSCLCMT_ITMNSCLCMTOTH_C);
	%concatoth(var=ITMNSCLCHXMT_OTH,oth=ITMNSCLCMTOTH,newvar=OTHER);
	SITE=catx(', ',ITMNSCLCMT_CITMNONE, ITMNSCLCMT_CITMCNS, ITMNSCLCMT_CITMBONESPN, ITMNSCLCMT_CITMSKIN, ITMNSCLCMT_CITMLUNG, 
				ITMNSCLCMT_CITMLIVER, ITMNSCLCMT_CITMSPLEEN, ITMNSCLCMT_CITMLYMNODES, ITMNSCLCMT_CITMCHSTWALL, ITMNSCLCMT_CITMESOPHAG, 
				ITMNSCLCMT_CITMSTOMACH, ITMNSCLCMT_CITMBREAST, ITMNSCLCMT_CITMOVARY, ITMNSCLCMT_CITMPANCREAS, ITMNSCLCMT_CITMADKIDNEY, 
				ITMNSCLCMT_CITMCOLON,ITMNSCLCMT_CITMRECTAL,OTHER);

	FLAG='NSCLC Staging at Time of Study Entry';
	keep &GlobalVars1 FLAG HISTOLOGY FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;

run;
data fa14;
	retain &GlobalVars1 FLAG HISTOLOGY FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	keep &GlobalVars1 FLAG HISTOLOGY FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	set fa20;
run; 

data faall_;
	set fa08 fa14;
run;

proc sort data=faall_; by SUBJECTNUMBERSTR __VISITNUM FLAG; run;

data pdata.faall(label='NSCLC History/NSCLC at Time of Study Entry');
	retain &GlobalVars1 FLAG HISTOLOGY FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	keep &GlobalVars1 FLAG HISTOLOGY FASTDTC NSCLCT NSCLCN NSCLCM OVSTG SITE;
	set faall_;
run;
 
*------------------------------------------------------------------------------------------>;
