start /w sas.exe -sysin rftstdtc.sas
start /w sas.exe -sysin dm.sas
start /w sas.exe -sysin ae.sas
start /w sas.exe -sysin bp.sas
start /w sas.exe -sysin cm.sas
start /w sas.exe -sysin cmrx.sas
start /w sas.exe -sysin dadm.sas
start /w sas.exe -sysin death.sas
start /w sas.exe -sysin disc.sas
start /w sas.exe -sysin dsexit.sas
start /w sas.exe -sysin ecg.sas
start /w sas.exe -sysin ecog.sas
start /w sas.exe -sysin exrit.sas
start /w sas.exe -sysin fl.sas
start /w sas.exe -sysin ic.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin lsnt.sas
start /w sas.exe -sysin lst.sas
start /w sas.exe -sysin mh.sas
start /w sas.exe -sysin ml.sas
start /w sas.exe -sysin pdfu.sas
start /w sas.exe -sysin peabn.sas
start /w sas.exe -sysin pet.sas
start /w sas.exe -sysin pk.sas
start /w sas.exe -sysin pkcyp.sas
start /w sas.exe -sysin radiol.sas
start /w sas.exe -sysin rs.sas
start /w sas.exe -sysin sv.sas
start /w sas.exe -sysin tbp.sas
start /w sas.exe -sysin vs.sas
start /w sas.exe -sysin lbchem.sas
start /w sas.exe -sysin lbhem.sas
start /w sas.exe -sysin lburin.sas
start /w sas.exe -sysin lbcoag.sas
start /w sas.exe -sysin lbhepa.sas
start /w sas.exe -sysin lbpreg.sas
start /w sas.exe -sysin lbbiom1.sas
start /w sas.exe -sysin lbbiom2.sas
start /w sas.exe -sysin lbbiom3.sas