start /w sas.exe -sysin dm.sas
start /w sas.exe -sysin ch.sas
start /w sas.exe -sysin cm.sas
start /w sas.exe -sysin cmrx1.sas
start /w sas.exe -sysin cmrx2.sas
start /w sas.exe -sysin cmrx3.sas
start /w sas.exe -sysin ex.sas
start /w sas.exe -sysin exbtk.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin death.sas
start /w sas.exe -sysin discbtk.sas
start /w sas.exe -sysin dseot.sas
start /w sas.exe -sysin dsexit.sas
start /w sas.exe -sysin enroll.sas
start /w sas.exe -sysin mh.sas
start /w sas.exe -sysin eye.sas
start /w sas.exe -sysin dh.sas
start /w sas.exe -sysin recons.sas
start /w sas.exe -sysin tx.sas
start /w sas.exe -sysin sched.sas
start /w sas.exe -sysin surghx.sas
start /w sas.exe -sysin survival.sas
start /w sas.exe -sysin up.sas
start /w sas.exe -sysin lab.sas
start /w sas.exe -sysin lbbio.sas
start /w sas.exe -sysin lbtbnk.sas
start /w sas.exe -sysin lbpreg.sas
start /w sas.exe -sysin ae.sas
start /w sas.exe -sysin eg.sas
start /w sas.exe -sysin pe.sas
start /w sas.exe -sysin pk.sas
start /w sas.exe -sysin vs.sas
start /w sas.exe -sysin ml.sas
start /w sas.exe -sysin xd.sas
start /w sas.exe -sysin xm.sas
start /w sas.exe -sysin xo.sas
start /w sas.exe -sysin rs.sas
start /w sas.exe -sysin invpd.sas
start /w sas.exe -sysin pdfu.sas
start /w sas.exe -sysin dssym.sas
start /w sas.exe -sysin kps.sas
start /w sas.exe -sysin pd.sas
start /w sas.exe -sysin opth.sas