start /w sas.exe -sysin rfstdtc.sas
start /w sas.exe -sysin dm.sas
start /w sas.exe -sysin ae.sas
start /w sas.exe -sysin bh.sas
start /w sas.exe -sysin buccal.sas
start /w sas.exe -sysin cm.sas
start /w sas.exe -sysin death.sas
start /w sas.exe -sysin disc.sas
start /w sas.exe -sysin ds.sas
start /w sas.exe -sysin ecog.sas
start /w sas.exe -sysin eg.sas
start /w sas.exe -sysin enroll.sas
start /w sas.exe -sysin eot.sas
start /w sas.exe -sysin ex.sas
start /w sas.exe -sysin exmedi.sas
start /w sas.exe -sysin ic.sas
start /w sas.exe -sysin ie.sas
start /w sas.exe -sysin img.sas
start /w sas.exe -sysin lab.sas
start /w sas.exe -sysin lsnew.sas
start /w sas.exe -sysin lsntg1.sas
start /w sas.exe -sysin lsntg2.sas
start /w sas.exe -sysin lstg1.sas
start /w sas.exe -sysin lstg2.sas
start /w sas.exe -sysin maligoth.sas
start /w sas.exe -sysin mh.sas
start /w sas.exe -sysin nh.sas
start /w sas.exe -sysin pdbtk1.sas
start /w sas.exe -sysin pdbtk2.sas
start /w sas.exe -sysin pdmedi1.sas
start /w sas.exe -sysin pdmedi2.sas
start /w sas.exe -sysin pe.sas
start /w sas.exe -sysin pefu.sas
start /w sas.exe -sysin ph.sas
start /w sas.exe -sysin pkbtk1.sas
start /w sas.exe -sysin pkbtk2.sas
start /w sas.exe -sysin pkmedi1.sas
start /w sas.exe -sysin pkmedi2.sas
start /w sas.exe -sysin pregl.sas
start /w sas.exe -sysin pridrg.sas
start /w sas.exe -sysin prirad.sas
start /w sas.exe -sysin prisg.sas
start /w sas.exe -sysin rs.sas
start /w sas.exe -sysin rsyn1.sas
start /w sas.exe -sysin rsyn2.sas
start /w sas.exe -sysin sg.sas
start /w sas.exe -sysin su.sas
start /w sas.exe -sysin subdrg.sas
start /w sas.exe -sysin subrad.sas
start /w sas.exe -sysin surv.sas
start /w sas.exe -sysin survyn.sas
start /w sas.exe -sysin tbx.sas
start /w sas.exe -sysin term.sas
start /w sas.exe -sysin unsched.sas
start /w sas.exe -sysin visit.sas
start /w sas.exe -sysin vs.sas