
/*****************************************************************************
 * AUTO-GENERATED FILE
 *****************************************************************************
 * Project:  ArQule ARQ 087-101 Study
 * Protocol: ARQ 087-101
 * Client:   ArQule, Inc.
 *****************************************************************************
 * Nextrials Prism(tm) Data Timestamp:             Tue, Oct  1, 2013 00:31 UTC 
 * Generated by prism2sas on:                      Tue, Oct  1, 2013 09:06 UTC 
 * Nextrials Prism(tm) 3.0.5 released on:              February 15, 2013       
 * Nextrials uses SAS v 8.2
 *****************************************************************************/


proc format;

/* arql/014/$lbco - Lab Result */
  value $lbco
    'coag_ptt' = "PTT"
    'coag_pt' = "PT"
    'coag_inr' = "INR"
  ;

/* arql/014/$lbth - Lab Result */
  value $lbth
    'thyroid_tsh' = "Thyroid Stimulating Hormone (TSH)"
    'thyroid_t3' = "Triiodothyronine (Total T3)"
    'thyroid_t4' = "Thyroxine (T4)"
  ;

/* arql/014/$lbu - Lab Result */
  value $lbu
    'urine_glucose' = "Glucose"
    'urine_protein' = "Protein"
    'urine_microscopic_wbc' = "WBC"
    'urine_microscopic_rbc' = "RBC"
    'urine_specific_gravity' = "Specific Gravity"
  ;

/* arql/014/$ltchem - Chemistry Panel Lab Tests */
  value $ltchem
    'chem_bilirubin_total' = "Total Bilirubin"
    'chem_calcium' = "Calcium"
    'chem_albumin' = "Albumin"
    'chem_bicarbonate' = "Bicarbonate"
    'chem_alt' = "ALT"
    'chem_bilirubin_total_direct' = "Direct Bilirubin"
    'chem_glucose' = "Glucose"
    'chem_creatinine' = "Creatinine"
    'chem_sodium' = "Sodium"
    'chem_potassium' = "Potassium"
    'chem_magnesium' = "Magnesium"
    'chem_bun' = "Blood Urea Nitrogen (BUN)"
    'chem_uric_acid' = "Uric Acid"
    'chem_hemoglobin_a1c' = "Glycated Hemoglobin (HbA1c)"
    'chem_ast' = "AST"
    'chem_ldh' = "Lactate Dehydrogenase (LDH)"
    'chem_phosphorus' = "Phosphorus (Phosphate)"
    'chem_total_protein' = "Total Protein"
    'chem_alkaline_phosphatase' = "Alkaline Phosphatase"
    'chem_chloride' = "Chloride"
  ;

/* arql/014/$lthem - Hematology Panel Lab Tests */
  value $lthem
    'hem_hematocrit' = "Hematocrit"
    'hem_basophils' = "Basophils (%)"
    'hem_monocytes' = "Monocytes (%)"
    'hem_eosinophils_absolute' = "Eosinophils (Absolute)"
    'hem_lymphocytes' = "Lymphocytes (%)"
    'hem_bands_absolute' = "Bands (Absolute)"
    'hem_bands' = "Bands (%)"
    'hem_hemoglobin' = "Hemoglobin"
    'hem_wbc' = "WBC"
    'hem_neutrophils_absolute' = "Neutrophils (Absolute)"
    'hem_platelets' = "Platelets"
    'hem_rbc' = "RBC"
    'hem_neutrophils' = "Neutrophils (%)"
    'hem_basophils_absolute' = "Basophils (Absolute)"
    'hem_reticulocytes_absolute' = "Reticulocyte Count (Absolute)"
    'hem_reticulocytes' = "Reticulocyte (%)"
    'hem_monocytes_absolute' = "Monocytes (Absolute)"
    'hem_eosinophils' = "Eosinophils (%)"
    'hem_lymphocytes_absolute' = "Lymphocytes (Absolute)"
  ;

/* arql/014/$map_dic - Mapping Dictionary */
  value $map_dic
    'md70' = "MedDRA 7.0"
    'WHODDxxxB September 1, 2009' = "WHODDxxxB September 1, 2009"
    'WHODDxxxB 3Q2004' = "WHODrugB 3Q2004"
    'WHODDxxxB Sept 1, 2007' = "WHODDxxxB Sept 1, 2007"
    'WHODDxxxB June 1, 2006' = "WHODDxxxB June 1, 2006"
    'WHODDxxxB 1Q2004' = "WHODrugB 1Q2004"
    'WHODDxxxC 1Q2005' = "WHODrugC 1Q2005"
    'md141' = "MedDRA 14.1"
    'md71' = "MedDRA 7.1"
    'md81' = "MedDRA 8.1"
    'md11' = "MedDRA 10.1"
    'md131' = "MedDRA 13.1"
    'WHODDxxxB 4Q2005' = "WHODrugB 4Q2005"
    'md90' = "MedDRA 9.0"
    'md120' = "MedDRA 12.0"
    'WHODDxxxB September 1, 2011' = "WHODDxxxB September 1, 2011"
    'WHODDxxxB 4Q2004' = "WHODrugB 4Q2004"
    'WHODDxxxB September 1, 2008' = "WHODDxxxB September 1, 2008"
    'WHODDxxxB June 1, 2012' = "WHODDxxxB June 1, 2012"
    'WHODDxxxC 2Q2004' = "WHODrugC 2Q2004"
    'md12' = "MedDRA 10.2"
    'WHODDxxxB 1Q2005' = "WHODrugB 1Q2005"
    'WHODDxxxB March 1, 2006' = "WHODDxxxB March 1, 2006"
    'md151' = "MedDRA 15.1"
    'WHODDxxxB December 1, 2012' = "WHODDxxxB December 1, 2012"
    'WHODDxxxC 1Q2004' = "WHODrugC 1Q2004"
    'WHODDxxxB March 1, 2008' = "WHODDxxxB March 1, 2008"
    'md10' = "MedDRA 10.0"
    'md91' = "MedDRA 9.1"
    'WHODDxxxC June 1, 2006' = "WHODDxxxC June 1, 2006"
    'md111' = "MedDRA 11.1"
    'WHODDxxxC 3Q2004' = "WHODrugC 3Q2004"
    'md60' = "MedDRA 6.0"
    'WHODDxxxB March 1, 2007' = "WHODDxxxB March 1, 2007"
    'WHODDxxxB December 1, 2006' = "WHODDxxxB December 1, 2006"
    'WHODDxxxB Dec 1, 2007' = "WHODDxxxB Dec 1, 2007"
    'WHODDxxxB 2Q2004' = "WHODrugB 2Q2004"
    'WHODDxxxC September 1, 2006' = "WHODDxxxC September 1, 2006"
    'md110' = "MedDRA 11.0"
    'md121' = "MedDRA 12.1"
    'WHODDxxxB June 1, 2007' = "WHODDxxxB June 1, 2007"
    'WHODDxxxB 1Q2006' = "WHODrugB 1Q2006"
    'md80' = "MedDRA 8.0"
    'WHODDxxxC December 1, 2006' = "WHODDxxxC December 1, 2006"
    'md51' = "MedDRA 5.1"
    'WHODDxxxC March 1, 2006' = "WHODDxxxC March 1, 2006"
    'md13' = "MedDRA 10.3"
    'WHODDxxxB June 1, 2008' = "WHODDxxxB June 1, 2008"
    'md50' = "MedDRA 5.0"
    'WHODDxxxB March 1, 2010' = "WHODDxxxB March 1, 2010"
    'WHODDxxxB September 1, 2006' = "WHODDxxxB September 1, 2006"
    'md61' = "MedDRA 6.1"
    'md140' = "MedDRA 14.0"
    'WHODDxxxB December 1, 2011' = "WHODDxxxB December 1, 2011"
    'md150' = "MedDRA 15.0"
    'WHODDxxxB December 1, 2008' = "WHODDxxxB December 1, 2008"
    'WHODDxxxB December 1, 2010' = "WHODDxxxB December 1, 2010"
  ;

/* arql/014/$map_pro - Mapping Product */
  value $map_pro
    'dsn2' = "dsNavigator 2.x"
    'dsn3' = "dsNavigator 3.x"
  ;

/* arql/014/$map_sou - dsNavigator Source */
  value $map_sou
    'S' = "Synonym match"
    '*' = "Manual encode"
    'A' = "Autoencoded"
    'X' = "Exact match"
  ;

/* arql/014/NoYes -  */
  value NoYes
    0 = "No"
    1 = "Yes"
  ;

/* arql/014/abn - Abnormal */
  value abn
    1 = "Abnormal Checked"
  ;

/* arql/014/aeact_a - Dose/Treatment not changed (continued without
interruption or change) */
  value aeact_a
    1 = "Dose/Treatment not changed (continued without interruption or change) Checked"
  ;

/* arql/014/aeact_b - Dose Reduced Without Interruption */
  value aeact_b
    1 = "Dose Reduced Without Interruption Checked"
  ;

/* arql/014/aeact_c - Treatment temporarily interrupted */
  value aeact_c
    1 = "Treatment temporarily interrupted Checked"
  ;

/* arql/014/aeact_d - Treatment temporarily interrupted then reduced */
  value aeact_d
    1 = "Treatment temporarily interrupted then reduced Checked"
  ;

/* arql/014/aeact_e - Treatment permanently discontinued */
  value aeact_e
    1 = "Treatment permanently discontinued Checked"
  ;

/* arql/014/aeact_f - N/A (Treatment discontinued/interrupted prior to onset of
the AE) */
  value aeact_f
    1 = "N/A (Treatment discontinued/interrupted prior to onset of the AE) Checked"
  ;

/* arql/014/aeact_g - Unknown */
  value aeact_g
    1 = "Unknown Checked"
  ;

/* arql/014/aeactoth - Other Action Taken */
  value aeactoth
    1 = "None"
    2 = "Medication Required"
    99 = "Other (Specify)"
  ;

/* arql/014/aecaus - Causality */
  value aecaus
    1 = "Related"
    2 = "Unrelated"
  ;

/* arql/014/aenci - NCI CTCAE Grade */
  value aenci
    1 = "1 (Mild)"
    2 = "2 (Moderate)"
    3 = "3 (Severe)"
    4 = "4 (Life-threatening)"
    5 = "5 (Fatal)"
  ;

/* arql/014/aeongo - Ongoing */
  value aeongo
    1 = "Ongoing Checked"
  ;

/* arql/014/aeout - Outcome */
  value aeout
    1 = "Recovered/Resolved"
    2 = "Resolved/ Resolved with Sequelae"
    3 = "Not Recovered/Not Resolved"
    4 = "Fatal"
    5 = "Unknown"
  ;

/* arql/014/cbaaacfc - Locked Flag */
  value cbaaacfc
    0 = "Unlocked"
    1 = "Locked"
  ;

/* arql/014/chgrade - Grade */
  value chgrade
    1 = "Well Differentiated"
    2 = "Moderately Differentiated"
    3 = "Poorly Differentiated/Undifferentiated"
    99 = "Unknown"
  ;

/* arql/014/chstgd - Tumor Staging at Diagnosis */
  value chstgd
    1 = "0"
    2 = "I"
    3 = "II"
    4 = "III"
    5 = "IV"
    99 = "Other (Specify)"
  ;

/* arql/014/chtype - Type of Cancer */
  value chtype
    1 = "AIDS-related Malignancy and Condition"
    2 = "Bone Neoplasm"
    3 = "Breast Neoplasm"
    4 = "CNS Neoplasm (Primary Tumor)"
    5 = "CNS-excluded Nervous System Neoplasm and Disorder"
    6 = "Endocrine Neoplasm"
    7 = "Eye Neoplasm"
    8 = "Gastrointestinal Neoplasm"
    9 = "Germ Cell Neoplasm"
    10 = "Head and Neck Neoplasm"
    11 = "Hematopoietic Neoplasm (excluding Leukemia, Lymphoma, Myeloma)"
    12 = "Hematopoietic Neoplasm/Leukemia"
    13 = "Hematopoietic Neoplasm/Lymphoma"
    14 = "Hematopoietic Neoplasm/Myeloma"
    15 = "Immune Disorder (excluding AIDS and malignancy)"
    16 = "Kidney Neoplasm"
    17 = "Lung, Mediastinal and Pleural Neoplasm"
    18 = "Miscellaneous Neoplasm"
    19 = "Reproductive System Neoplasm, Female"
    20 = "Reproductive System Neoplasm, Male"
    21 = "Skin Neoplasm"
    22 = "Soft Tissue Neoplasm"
    23 = "Urothelial Tract Neoplasm"
  ;

/* arql/014/cmae - Is this for an AE? */
  value cmae
    1 = "Is this for an AE? Checked"
  ;

/* arql/014/cmong - Ongoing */
  value cmong
    1 = "Ongoing Checked"
  ;

/* arql/014/cmprior - Taken Prior to Study */
  value cmprior
    1 = "Taken Prior to Study Checked"
  ;

/* arql/014/cmroute - Route */
  value cmroute
    1 = "By Mouth"
    2 = "Inhaled"
    3 = "Subcutaneous"
    4 = "Intramuscular"
    5 = "Nasal"
    6 = "Topical"
    7 = "Intravenous"
    8 = "Transdermal"
    99 = "Other (Specify)"
  ;

/* arql/014/dthcod - Primary Cause of Death */
  value dthcod
    1 = "Progression of Disease (PD)"
    2 = "Adverse Event"
    99 = "Other (Specify)"
  ;

/* arql/014/eabacdfe - Tumor Marker Collected */
  value eabacdfe
    0 = "No (Specify)"
    1 = "Yes"
  ;

/* arql/014/efedaafa - Approved */
  value efedaafa
    0 = "Not Approved"
    1 = "Approved"
  ;

/* arql/014/egmeth - Method Used */
  value egmeth
    1 = "12 Lead ECG"
    99 = "Other (Specify)"
  ;

/* arql/014/esps - Performance Status */
  value esps
    0 = "Grade 0 = Fully Active"
    1 = "Grade 1 = Restricted in Physical Strenuous Activity"
    2 = "Grade 2 = Ambulatory and Capable of Self-care"
    3 = "Grade 3 = Capable of Only Limited Self-care"
    4 = "Grade 4 = Completely Disabled"
    5 = "Grade 5 = Dead"
  ;

/* arql/014/ethnicty - Ethnicity */
  value ethnicty
    1 = "Hispanic or Latino"
    2 = "Not Hispanic or Latino"
  ;

/* arql/014/ffcfeeda - Has Subject Started New Cancer Therapy */
  value ffcfeeda
    0 = "No"
    1 = "Yes (Specify)"
  ;

/* arql/014/ffefccbd - CS Abnormal Findings */
  value ffefccbd
    0 = "No"
    1 = "Yes (See instruction above)"
  ;

/* arql/014/heightu - Height Unit */
  value heightu
    1 = "Cm"
    2 = "In"
  ;

/* arql/014/lbabn - Abnormal */
  value lbabn
    1 = "Abnormal Checked"
  ;

/* arql/014/lbcs - Clinically Significant */
  value lbcs
    1 = "Clinically Significant Checked"
  ;

/* arql/014/lbnd - Not Done */
  value lbnd
    1 = "Not Done Checked"
  ;

/* arql/014/lbrel - Relation */
  value lbrel
    1 = "High"
    2 = "Low"
  ;

/* arql/014/meyn - Type of Test */
  value meyn
    1 = "MUGA"
    2 = "Echocardiogram"
  ;

/* arql/014/mhcont - Mark if Ongoing */
  value mhcont
    1 = "Mark if Ongoing Checked"
  ;

/* arql/014/nable - Not Assessable (Specify) */
  value nable
    1 = "Not Assessable (Specify) Checked"
  ;

/* arql/014/ntasmt - Status */
  value ntasmt
    1 = "Present"
    2 = "Absent"
    3 = "New Lesion"
    4 = "Unequivocal Progression"
  ;

/* arql/014/ntnotac - Not Assessed (Specify) */
  value ntnotac
    1 = "Not Assessed (Specify) Checked"
  ;

/* arql/014/pdasamc - Type of Sample Collected */
  value pdasamc
    1 = "Tissue Block"
    2 = "Paraffin Embedded Slides"
  ;

/* arql/014/pdaship - Type of Tissue Shipped */
  value pdaship
    1 = "Fresh Frozen Tissue"
    2 = "Tissue Block"
    3 = "Paraffin Embedded Slides"
    99 = "Other (Specify)"
  ;

/* arql/014/pdatyp - Type of Biopsy */
  value pdatyp
    1 = "Surgical Resection"
    2 = "Core Needle Biopsy"
    3 = "Fine Needle Aspiration"
    99 = "Other (Specify)"
  ;

/* arql/014/pdreas - Deviation/Violation Reason */
  value pdreas
    1 = "Eligibility Criteria Violation/Deviation"
    2 = "Lab Test Not Done"
    3 = "Lab Test Not Done Within Specified Time Frame"
    4 = "Procedure Not Done"
    5 = "Procedure Not Done Within Specified Time Frame"
    6 = "Over dose"
    99 = "Other (Specify)"
  ;

/* arql/014/pk15nd - Not Done */
  value pk15nd
    1 = "Not Done Checked"
  ;

/* arql/014/pk23nd - Not Done */
  value pk23nd
    1 = "Not Done Checked"
  ;

/* arql/014/pk2tmpt - Planned Time */
  value pk2tmpt
    1 = "Cycle 1 Day 22 Pre-Dose"
    2 = "Cycle 1 Day 22 - 1 Hour Post Dose"
    3 = "Cycle 1 Day 22 - 2 Hours Post Dose"
    4 = "Cycle 1 Day 22 - 4 Hours Post Dose"
    5 = "Cycle 1 Day 22 - 6 Hours Post Dose"
    6 = "Cycle 1 Day 22 - 8 Hours Post Dose"
    7 = "Cycle 1 Day 22 - 10 Hours Post Dose"
    8 = "Cycle 1 Day 22 - 12 Hours Post Dose"
  ;

/* arql/014/pk3tmpt - Planned Time */
  value pk3tmpt
    1 = "Day 1 - Pre-dose"
    2 = "Day 1 - 1 Hour Post Dose"
    3 = "Day 1 - 2 Hours Post Dose"
    4 = "Day 1 - 4 Hours Post Dose"
    5 = "Day 1 - 6 Hours Post Dose"
    6 = "Day 1 - 8 Hours Post Dose"
    7 = "Day 1 - 10 Hours Post Dose"
    8 = "Day 1 - 12 Hours Post Dose"
    9 = "Day 2 - 24 Hours Post Dose"
  ;

/* arql/014/pk4tmpt - Planned Time */
  value pk4tmpt
    1 = "Cycle 1 Day 22 Pre-Dose"
    2 = "Cycle 1 Day 22 - 1 Hour Post Dose"
    3 = "Cycle 1 Day 22 - 2 Hours Post Dose"
    4 = "Cycle 1 Day 22 - 4 Hours Post Dose"
    5 = "Cycle 1 Day 22 - 6 Hours Post Dose"
    6 = "Cycle 1 Day 22 - 8 Hours Post Dose"
    7 = "Cycle 1 Day 22 - 10 Hours Post Dose"
    8 = "Cycle 1 Day 22 - 12 Hours Post Dose"
  ;

/* arql/014/pk8nd - Not Done */
  value pk8nd
    1 = "Not Done Checked"
  ;

/* arql/014/pknd - Not Done */
  value pknd
    1 = "Not Done Checked"
  ;

/* arql/014/pkond - Not Done */
  value pkond
    1 = "Not Done Checked"
  ;

/* arql/014/pkotp - Cycle and Day */
  value pkotp
    1 = "Cycle 2 Day 1"
    2 = "Cycle 2 Day 15"
    3 = "Cycle 3 Day 1"
    4 = "Cycle 3 Day 15"
    5 = "Cycle 4 Day 1"
    6 = "Cycle 4 Day 15"
    7 = "Cycle 5 Day 1"
    8 = "Cycle 5 Day 15"
    9 = "Cycle 6 Day 1"
    10 = "Cycle 6 Day 15"
    11 = "End of Treatment"
    99 = "Other (Specify)"
  ;

/* arql/014/pktmpt - Planned Time */
  value pktmpt
    1 = "Day 1 - Pre-dose"
    2 = "Day 1 - 1 Hour Post Dose"
    3 = "Day 1 - 2 Hours Post Dose"
    4 = "Day 1 - 4 Hours Post Dose"
    5 = "Day 1 - 6 Hours Post Dose"
    6 = "Day 1 - 8 Hours Post Dose"
    7 = "Day 1 - 10 Hours Post Dose"
    8 = "Day 1 - 12 Hours Post Dose"
    9 = "Day 2 - 24 Hours Post Dose"
    10 = "Day 3 - 48 Hours Post Dose"
    11 = "Day 4 - 72 Hours Post Dose"
  ;

/* arql/014/prbest - Best Response */
  value prbest
    1 = "Complete Response"
    2 = "Partial Response"
    3 = "Stable Disease"
    4 = "Progressive Disease"
    5 = "Not Applicable"
    6 = "Not Evaluable"
    7 = "Unknown"
  ;

/* arql/014/pregmeth - Pregnancy Test Method */
  value pregmeth
    1 = "Serum"
    2 = "Urine"
  ;

/* arql/014/pregres - Pregnancy Test Results */
  value pregres
    1 = "Negative"
    2 = "Positive"
  ;

/* arql/014/pregynna - Was a Pregnancy Test Done */
  value pregynna
    0 = "No"
    1 = "Yes"
    2 = "N/A"
  ;

/* arql/014/prtype - Type of Radiotherapy */
  value prtype
    1 = "External Beam Radiation Therapy (EBRT)"
    2 = "3-Dimensional Conformal Radiation Therapy (3-D-CRT)"
    3 = "Intensity-Modulated Radiation Therapy (IMRT)"
    4 = "Image-Guided Radiation Therapy (IGRT)"
    5 = "Stereotactic Body Radiation Therapy (SBRT)"
    6 = "Stereotactic Radiosurgery (SRS)"
    7 = "Proton Therapy"
    8 = "Brachytherapy"
    99 = "Other (Specify)"
  ;

/* arql/014/prunit - Dose Unit */
  value prunit
    1 = "cGy"
    2 = "Gy"
  ;

/* arql/014/psfreq - Frequency */
  value psfreq
    1 = "Once a Day"
    2 = "Twice a Day"
    3 = "Three Times a Day"
    4 = "Continuous IV"
    5 = "As Needed"
    6 = "Every Other Day"
    7 = "One Time Only"
    99 = "Other (Specify)"
  ;

/* arql/014/pstype - Type of Therapy */
  value pstype
    1 = "Chemotherapy"
    2 = "Small Molecule Target Therapy"
    3 = "Immunotherapy"
    4 = "Hormonal Therapy"
    99 = "Other (Specify)"
  ;

/* arql/014/psunit - Dose Units */
  value psunit
    1 = "Tablet"
    2 = "Capsule"
    3 = "mg/m2"
    4 = "mg/kg"
    5 = "mg"
    6 = "IU"
    7 = "gtt"
    8 = "puffs"
    9 = "units"
    10 = "ug"
    11 = "g"
    12 = "Not Applicable"
    13 = "Unknown"
    99 = "Other (Specify)"
  ;

/* arql/014/pvnum - Protocol Version */
  value pvnum
    1 = "Original"
    2 = "Amendment (Specify)"
  ;

/* arql/014/qtcform - QTc Formula */
  value qtcform
    1 = "Bazett's"
    2 = "Fridericia's"
    99 = "Other (Specify)"
  ;

/* arql/014/race - Race */
  value race
    1 = "American Indian or Alaska Native"
    2 = "Asian"
    3 = "Black or African American"
    4 = "Native Hawaiian or other Pacific Islander"
    5 = "White"
    99 = "Other (Specify)"
  ;

/* arql/014/result - Results */
  value result
    1 = "Normal"
    2 = "Abnormal (Specify)"
  ;

/* arql/014/rsnterm - Discontinuation Reason */
  value rsnterm
    1 = "Clinical disease progression"
    2 = "Radiological disease progression (per RECIST)"
    3 = "Adverse Event/SAE (MUST be recorded on the AE CRF)"
    4 = "Lost to follow-up"
    5 = "Withdrawal by the subject"
    6 = "Physician's decision"
    7 = "Protocol violation"
    8 = "Death"
    9 = "Study terminated by the sponsor"
    99 = "Other (Specify)"
  ;

/* arql/014/sdfreq - Starting Dose Frequency */
  value sdfreq
    1 = "QD"
    3 = "QOD"
    99 = "Other (Specify)"
  ;

/* arql/014/sdhdrn - Dose Modify Reason */
  value sdhdrn
    1 = "Protocol Planned Dose Modification"
    2 = "Adverse Event - complete AE form"
    3 = "Overdose or Missed Dose"
    99 = "Other (Specify)"
  ;

/* arql/014/sdmodify - Type of Dose Modification */
  value sdmodify
    1 = "Dose Increased"
    2 = "Dose Temporarily Interrupted"
    3 = "Dose Reduced"
    99 = "Other (Specify)"
  ;

/* arql/014/sex - Sex */
  value sex
    0 = "Female"
    1 = "Male"
  ;

/* arql/014/sfnd - Reason Not Performed */
  value sfnd
    1 = "Withdrawal by Subject"
    2 = "Lost to Follow-up"
    3 = "Started other anti-cancer therapy"
    4 = "Death"
    99 = "Other (Specify)"
  ;

/* arql/014/sgdiag - Diagnostic */
  value sgdiag
    1 = "Diagnostic Checked"
  ;

/* arql/014/sgploc - Anatomical Location */
  value sgploc
    1 = "Abdomen"
    2 = "Adrenal Gland - Left"
    3 = "Adrenal Gland - Right"
    4 = "Biliary Tract"
    5 = "Bladder (Urinary)"
    6 = "Brain"
    7 = "Breast - Left"
    8 = "Breast - Right"
    9 = "Cervix"
    10 = "Chest Wall"
    11 = "Colon - Ascending"
    12 = "Colon - Sigmoid"
    13 = "Colon - Transverse"
    14 = "Esophagus"
    15 = "Fallopian Tubes"
    16 = "Gallbladder"
    17 = "Head and Neck"
    18 = "Heart"
    19 = "Kidney - Left"
    20 = "Kidney - Right"
    21 = "Liver"
    22 = "Lung LLL"
    23 = "Lung LML"
    24 = "Lung LUL"
    25 = "Lung RLL"
    26 = "Lung RML"
    27 = "Lung RUL"
    28 = "Lymph Node(s) (Specify)"
    29 = "Mediastinum"
    30 = "Muscle"
    31 = "Oral"
    32 = "Ovary - Left"
    33 = "Ovary - Right"
    34 = "Pancreas - Head"
    35 = "Pancreas - Body"
    36 = "Peritoneum"
    37 = "Pleura"
    38 = "Prostate"
    39 = "Rectum"
    40 = "Skin"
    41 = "Spleen"
    42 = "Testis - Left"
    43 = "Testis - Right"
    44 = "Uterus"
    99 = "Other (Specify)"
  ;

/* arql/014/sgther - Therapeutic */
  value sgther
    1 = "Therapeutic Checked"
  ;

/* arql/014/test - ECG Test Name */
  value test
    1 = "Summary (mean) Ventricular Rate"
    2 = "PR"
    3 = "QRS"
    4 = "QT"
    5 = "QTc"
  ;

/* arql/014/tm_unit - Unit - Reported */
  value tm_unit
    1 = "ng/dL"
    2 = "ng/mL"
    3 = "U/mL"
    4 = "U/L"
    5 = "IU/L"
    6 = "IU/mL"
    7 = "MIU/ml"
    8 = "Mu/ml"
    9 = "mcg/L"
    99 = "Other (Specify)"
  ;

/* arql/014/tmln - Check if lesion is a lymph node (LN) */
  value tmln
    1 = "Check if lesion is a lymph node (LN) Checked"
  ;

/* arql/014/tmmeth - Assessment Method */
  value tmmeth
    1 = "Conventional CT Scan"
    2 = "Spiral CT Scan"
    3 = "MRI"
    4 = "Physical Exam"
    5 = "PET Scan"
    6 = "X-ray"
    7 = "Bone Scan"
    8 = "Ultrasonography"
    9 = "Non-Contrast CT"
    10 = "Non-Contrast MRI"
    99 = "Other (Specify)"
  ;

/* arql/014/tmnotac - Not Assessed (Specify) */
  value tmnotac
    1 = "Not Assessed (Specify) Checked"
  ;

/* arql/014/tmresp - Response Target Lesions */
  value tmresp
    1 = "Complete Response"
    2 = "Partial Response"
    3 = "Stable Disease"
    4 = "Progressive Disease"
    5 = "Not all Evaluated"
    6 = "Unknown"
    7 = "Not Applicable"
  ;

/* arql/014/tmtest - Tumor Markers Lab Tests */
  value tmtest
    1 = "CEA"
    2 = "PSA"
    3 = "aFP"
    4 = "CA27.29"
    5 = "CA19.9"
    6 = "CA15.3"
    7 = "CA125"
    8 = "bHCG"
    99 = "Other (Specify)"
  ;

/* arql/014/tmvis - Event Code */
  value tmvis
    1 = "Pre-Study"
    2 = "Cycle 3"
    3 = "Cycle 5"
    4 = "Cycle 7"
    5 = "Cycle 9"
    6 = "Cycle 11"
    7 = "Cycle 13"
    8 = "End of Study"
    99 = "Unscheduled (Specify)"
  ;

/* arql/014/unit - Unit */
  value unit
    1 = "Beats/min"
    2 = "msec"
  ;

/* arql/014/unlabc - Chemistry */
  value unlabc
    1 = "Chemistry Checked"
  ;

/* arql/014/unlabcg - Coagulation */
  value unlabcg
    1 = "Coagulation Checked"
  ;

/* arql/014/unlabgh - Thyroid Function Test */
  value unlabgh
    1 = "Thyroid Function Test Checked"
  ;

/* arql/014/unlabh - Hematology */
  value unlabh
    1 = "Hematology Checked"
  ;

/* arql/014/unlabua - Urinalysis */
  value unlabua
    1 = "Urinalysis Checked"
  ;

/* arql/014/unmuga - MUGA/Echocardiogram */
  value unmuga
    1 = "MUGA/Echocardiogram Checked"
  ;

/* arql/014/unpreg - Pregnancy Test */
  value unpreg
    1 = "Pregnancy Test Checked"
  ;

/* arql/014/unsecg - 12-Lead Electrocardiogram */
  value unsecg
    1 = "12-Lead Electrocardiogram Checked"
  ;

/* arql/014/unsecog - ECOG */
  value unsecog
    1 = "ECOG Checked"
  ;

/* arql/014/unspe - Physical Examination */
  value unspe
    1 = "Physical Examination Checked"
  ;

/* arql/014/unstumor - Tumor Marker */
  value unstumor
    1 = "Tumor Marker Checked"
  ;

/* arql/014/unsvs - Vital Sign */
  value unsvs
    1 = "Vital Sign Checked"
  ;

/* arql/014/vsbpnd - Not Done */
  value vsbpnd
    1 = "Not Done Checked"
  ;

/* arql/014/vshrnd - Not Done */
  value vshrnd
    1 = "Not Done Checked"
  ;

/* arql/014/vshtnd - Not Done */
  value vshtnd
    1 = "Not Done Checked"
  ;

/* arql/014/vsrespnd - Not Done */
  value vsrespnd
    1 = "Not Done Checked"
  ;

/* arql/014/vstempnd - Not Done */
  value vstempnd
    1 = "Not Done Checked"
  ;

/* arql/014/vstu - Temperature Unit */
  value vstu
    1 = "C"
    2 = "F"
  ;

/* arql/014/vswtnd - Not Done */
  value vswtnd
    1 = "Not Done Checked"
  ;

/* arql/014/vswtu - Weight Unit */
  value vswtu
    1 = "Kg"
    2 = "Lb"
  ;
value $VISIT
      'Pre-Study Visit' = 'Pre-Study'
      'Treatment Period 1 Week 0 (Day 1)' = 'Week 0 (Day 1)'
      'Treatment Period 1 Week 0 (Day 2)' = 'Week 0 (Day 2)'
      'Treatment Period 1 Week 0 (Day 3)' = 'Week 0 (Day 3)'
      'Treatment Period 1 Week 0 (Day 4)' = 'Week 0 (Day 4)'
      'Treatment Period 2 Cycle 1 (Day 1)' = 'Cycle 1 (Day 1)'
      'Treatment Period 2 Cycle 1 (Day 8)' = 'Cycle 1 (Day 8)'
      'Treatment Period 2 Cycle 1 (Day 15)' = 'Cycle 1 (Day 15)'
      'Treatment Period 2 Cycle 1 (Day 22)' = 'Cycle 1 (Day 22)'
      'Treatment Period 2 Cycle 1 (Day 23)' = 'Cycle 1 (Day 23)'
      'Treatment Period 2 Cycle #02 (Day 1)' = 'Cycle 2 (Day 1)'
      'Treatment Period 2 Cycle #02 (Day 15)' = 'Cycle 2 (Day 15)'
      'Treatment Period 2 Cycle #03 (Day 1)' = 'Cycle 3 (Day 1)'
      'Treatment Period 2 Cycle #03 (Day 15)' = 'Cycle 3 (Day 15)'
      'Treatment Period 2 Cycle #04 (Day 1)' = 'Cycle 4 (Day 1)'
      'Treatment Period 2 Cycle #04 (Day 15)' = 'Cycle 4 (Day 15)'
      'Treatment Period 2 Cycle #05 (Day 1)' = 'Cycle 5 (Day 1)'
      'Treatment Period 2 Cycle #05 (Day 15)' = 'Cycle 5 (Day 15)'
      'Treatment Period 2 Cycle #06 (Day 1)' = 'Cycle 6 (Day 1)'
      'Treatment Period 2 Cycle #06 (Day 15)' = 'Cycle 6 (Day 15)'
      'Treatment Period 2 Cycle #07 (Day 1)' = 'Cycle 7 (Day 1)'
      'Treatment Period 2 Cycle #07 (Day 15)' = 'Cycle 7 (Day 15)'
      'Treatment Period 2 Cycle #08 (Day 1)' = 'Cycle 8 (Day 1)'
      'Treatment Period 2 Cycle #08 (Day 15)' = 'Cycle 8 (Day 15)'
      'Treatment Period 2 Cycle #09 (Day 1)' = 'Cycle 9 (Day 1)'
      'Treatment Period 2 Cycle #09 (Day 15)' = 'Cycle 9 (Day 15)'
      'Treatment Period 2 Cycle #10 (Day 1)' = 'Cycle 10 (Day 1)'
      'Treatment Period 2 Cycle #10 (Day 15)' = 'Cycle 10 (Day 15)'
      'Continuous Dosing Cycle #01 (Day 1)' = 'Cycle 1 (Day 1)'
      'Continuous Dosing Cycle #01 (Day 15)' = 'Cycle 1 (Day 15)'
      'Continuous Dosing Cycle #01 (Day 2)' = 'Cycle 1 (Day 2)'
      'Continuous Dosing Cycle #01 (Day 22)' = 'Cycle 1 (Day 22)'
      'Continuous Dosing Cycle #01 (Day 23)' = 'Cycle 1 (Day 23)'
      'Continuous Dosing Cycle #01 (Day 8)' = 'Cycle 1 (Day 8)'
      'Continuous Dosing Cycle #02 (Day 1)' = 'Cycle 2 (Day 1)'
      'Continuous Dosing Cycle #02 (Day 15)' = 'Cycle 2 (Day 15)'
      'Continuous Dosing Cycle #03 (Day 1)' = 'Cycle 3 (Day 1)'
      'Continuous Dosing Cycle #03 (Day 15)' = 'Cycle 3 (Day 15)'
      'Continuous Dosing Cycle #04 (Day 1)' = 'Cycle 4 (Day 1)'
      'Continuous Dosing Cycle #04 (Day 15)' = 'Cycle 4 (Day 15)'
      'Continuous Dosing Cycle #05 (Day 1)' = 'Cycle 5 (Day 1)'
      'Continuous Dosing Cycle #05 (Day 15)' = 'Cycle 5 (Day 15)'
      'Continuous Dosing Cycle #06 (Day 1)' = 'Cycle 6 (Day 1)'
      'Continuous Dosing Cycle #06 (Day 15)' = 'Cycle 6 (Day 15)'
      'End of Treatment Visit' = 'End of Treatment'
      'Unscheduled Visit #01' = 'Unscheduled Visit'
      'Unscheduled Visit #02' = 'Unscheduled Visit'
      'Unscheduled Visit #03' = 'Unscheduled Visit'
      'Unscheduled Visit #04' = 'Unscheduled Visit'
      'Unscheduled Visit #05' = 'Unscheduled Visit'
      'Unscheduled Visit #06' = 'Unscheduled Visit'
      'Unscheduled Visit #07' = 'Unscheduled Visit'
      'Pre-Study' = 'Pre-Study'
      'Cycle 3' = 'Cycle 3'
      'Cycle 5' = 'Cycle 5'
      'Cycle 7' = 'Cycle 7'
      'Cycle 9' = 'Cycle 9'
      'Cycle 11' = 'Cycle 11'
      'Cycle 13' = 'Cycle 13'
      'Unscheduled Visit' = 'Unscheduled Visit'
      'Week 0 (Day 1)' = 'Week 0 (Day 1)'
      'Week 0 (Day 2)' = 'Week 0 (Day 2)'
      'Week 0 (Day 3)' = 'Week 0 (Day 3)'
      'Week 0 (Day 4)' = 'Week 0 (Day 4)'
      'Cycle 1 (Day 8)' = 'Cycle 1 (Day 8)'
      'Cycle 1 (Day 15)' = 'Cycle 1 (Day 15)'
      'Cycle 1 (Day 22)' = 'Cycle 1 (Day 22)'
      'Cycle 1 (Day 23)'='Cycle 1 (Day 23)'
      'Cycle 2 (Day 1)'='Cycle 2 (Day 1)'
      'Cycle 2 (Day 15)' = 'Cycle 2 (Day 15)'
      'Cycle 7 (Day 22)' = 'Cycle 7 (Day 22)'
      'Cycle 1 (Day 1)'='Cycle 1 (Day 1)'
      'End of Treatment' = 'End of Treatment'
      '30 Day Safety Follow-up' = '30 Day Safety Follow-up'
      'Other' = 'Other'
      . = " "
;

value $VNUM
      'Pre-Study Visit' = '0'
      'Treatment Period 1 Week 0 (Day 1)' = '1'
      'Treatment Period 1 Week 0 (Day 2)' = '2'
      'Treatment Period 1 Week 0 (Day 3)' = '3'
      'Treatment Period 1 Week 0 (Day 4)' = '4'
      'Treatment Period 2 Cycle 1 (Day 1)' = '5.01'
      'Treatment Period 2 Cycle 1 (Day 8)' = '5.08'
      'Treatment Period 2 Cycle 1 (Day 15)' = '5.15'
      'Treatment Period 2 Cycle 1 (Day 22)' = '5.22'
      'Treatment Period 2 Cycle 1 (Day 23)' = '5.23'
      'Treatment Period 2 Cycle #02 (Day 1)' = '6.01'
      'Treatment Period 2 Cycle #02 (Day 15)' = '6.15'
      'Treatment Period 2 Cycle #03 (Day 1)' = '7.01'
      'Treatment Period 2 Cycle #03 (Day 15)' = '7.15'
      'Treatment Period 2 Cycle #04 (Day 1)' = '8.01'
      'Treatment Period 2 Cycle #04 (Day 15)' = '8.15'
      'Treatment Period 2 Cycle #05 (Day 1)' = '9.01'
      'Treatment Period 2 Cycle #05 (Day 15)' = '9.15'
      'Treatment Period 2 Cycle #06 (Day 1)' = '10.01'
      'Treatment Period 2 Cycle #06 (Day 15)' = '10.15'
      'Treatment Period 2 Cycle #07 (Day 1)' = '11.01'
      'Treatment Period 2 Cycle #07 (Day 15)' = '11.15'
      'Treatment Period 2 Cycle #08 (Day 1)' = '12.01'
      'Treatment Period 2 Cycle #08 (Day 15)' = '12.15'
      'Treatment Period 2 Cycle #09 (Day 1)' = '13.01'
      'Treatment Period 2 Cycle #09 (Day 15)' = '13.15'
      'Treatment Period 2 Cycle #10 (Day 1)' = '14.01'
      'Treatment Period 2 Cycle #10 (Day 15)' = '14.15'
      'Continuous Dosing Cycle #01 (Day 1)' = '5.01'
      'Continuous Dosing Cycle #01 (Day 15)' = '5.15'
      'Continuous Dosing Cycle #01 (Day 2)' = '5.02'
      'Continuous Dosing Cycle #01 (Day 22)' = '5.22'
      'Continuous Dosing Cycle #01 (Day 23)' = '5.23'
      'Continuous Dosing Cycle #01 (Day 8)' = '5.08'
      'Continuous Dosing Cycle #02 (Day 1)' = '6.01'
      'Continuous Dosing Cycle #02 (Day 15)' = '6.15'
      'Continuous Dosing Cycle #03 (Day 1)' = '7.01'
      'Continuous Dosing Cycle #03 (Day 15)' = '7.15'
      'Continuous Dosing Cycle #04 (Day 1)' = '8.01'
      'Continuous Dosing Cycle #04 (Day 15)' = '8.15'
      'Continuous Dosing Cycle #05 (Day 1)' = '9.01'
      'Continuous Dosing Cycle #05 (Day 15)' = '9.15'
      'Continuous Dosing Cycle #06 (Day 1)' = '10.01'
      'Continuous Dosing Cycle #06 (Day 15)' = '10.05'
      'End of Treatment Visit' = '97'
      'Unscheduled Visit #01' = '99'
      'Unscheduled Visit #02' = '99'
      'Unscheduled Visit #03' = '99'
      'Unscheduled Visit #04' = '99'
      'Unscheduled Visit #05' = '99'
      'Unscheduled Visit #06' = '99'
      'Unscheduled Visit #07' = '99'
   ''=''
      'Cycle 1' = '5'
      'Cycle 2' = '6'
      'Cycle 3' = '7'
      'Cycle 4' = '8'
      'Cycle 5' = '9'
      'Cycle 6' = '10'
      'Cycle 7' = '11'
      'Cycle 8' = '12'
      'Cycle 9' = '13'
      'Cycle 10' = '14'
      'Cycle 11' = '15'
      'Cycle 12' = '16'
      'Cycle 13' = '17'
      'Unscheduled Visit' = '99'
      'Pre-Study' = '0'
      'Week 0 (Day 1)' = '1'
      'Week 0 (Day 2)' = '2'
      'Week 0 (Day 3)' = '3'
      'Week 0 (Day 4)' = '4'
      'Cycle 1 (Day 8)' = '5.08'
      'Cycle 1 (Day 15)' = '5.15'
      'Cycle 1 (Day 22)' = '5.22'
      'Cycle 1 (Day 23)'='5.23'
      'Cycle 2 (Day 1)'='6.01'
      'Cycle 2 (Day 15)' = '6.15'
      'Cycle 7 (Day 22)' = '11.22'
      'Cycle 1 (Day 1)'='5.01'
      'End of Treatment' = '97'
      '30 Day Safety Follow-up' = '98'
  'Other' = '999'
      . = " "
;

    value $lbhcod
        'hem_bands' = 'hem_1'
        'hem_bands_absolute' = 'hem_2'
        'hem_basophils' = 'hem_3'
        'hem_basophils_absolute' = 'hem_4'
        'hem_eosinophils' = 'hem_5'
        'hem_eosinophils_absolute' = 'hem_6'
        'hem_hematocrit' = 'hem_7'
        'hem_hemoglobin' = 'hem_8'
        'hem_lymphocytes' = 'hem_9'
        'hem_lymphocytes_absolute' = 'hem_10'
        'hem_monocytes' = 'hem_11'
        'hem_monocytes_absolute' = 'hem_12'
        'hem_neutrophils' = 'hem_13'
        'hem_neutrophils_absolute' = 'hem_14'
        'hem_platelets' = 'hem_15'
        'hem_rbc' = 'hem_16'
        'hem_reticulocytes' = 'hem_17'
        'hem_reticulocytes_absolute' = 'hem_18'
        'hem_wbc' = 'hem_19'
;

    invalue vnum
    'Pre-Study'               = 0
    'Week 0 (Day 1)'          = 0.1
    'Week 0 (Day 2)'          = 0.2
    'Week 0 (Day 3)'          = 0.3
    'Week 0 (Day 4)'          = 0.4
    'Cycle 1 (Day 1)'         = 1.01
    'Cycle 1 (Day 2)'         = 1.02
    'Cycle 1 (Day 8)'         = 1.08
    'Cycle 1 (Day 15)'        = 1.15
    'Cycle 1 (Day 22)'        = 1.22
    'Cycle 1 (Day 23)'        = 1.23
    'Cycle 2 (Day 1)'         = 2.01
    'Cycle 2 (Day 15)'        = 2.15
    'Cycle 3 (Day 1)'         = 3.01
    'Cycle 3 (Day 15)'        = 3.15
    'Cycle 4 (Day 1)'         = 4.01
    'Cycle 4 (Day 15)'        = 4.15
    'Cycle 5 (Day 1)'         = 5.01
    'Cycle 5 (Day 15)'        = 5.15
    'Cycle 6 (Day 1)'         = 6.01
    'Cycle 6 (Day 15)'        = 6.15
    'Cycle 7 (Day 1)'         = 7.01
    'Cycle 7 (Day 15)'        = 7.15
    'Cycle 8 (Day 1)'         = 8.01
    'End of Treatment'        = 97
    'Tumor Assessment'        = 98
    'Unscheduled Visit'       = 99
    '30 Day Safety Follow-up' = 101
    other                     = .
    ;


 run;
 /* EOF */
