*x 'RUN_ALL.bat&exit';
%include "_visitindex.sas";
%include "DM06.sas";
%include "MH06.sas" ;
%include "FAALL.sas" ;
%include "XC10.sas" ;
%include "XC12.sas" ;
%include "XC42.sas" ;
%include "YC11.sas" ;
%include "SC13.sas" ;
%include "TUTR.sas" ;
%include "TUTRN.sas" ;
%include "ECOG17.sas" ;
%include "DS49.sas" ;
%include "VSFU50.sas" ;
%include "RS52.sas" ;
%include "ZS54.sas" ;
%include "LBHEM.sas" ;
%include "LBURIN.sas" ;
%include "AE28.sas" ;
%include "SAE.sas" ;
%include "EG20.sas" ;
%include "ZB27.sas" ;
%include "CM28.sas" ;
%include "ZH37.sas" ;
%include "XC43.sas" ;
%include "YC44.sas" ;
%include "VSALL.sas" ;
%include "PEALL.sas" ;
%include "IE.sas";
/*%include "QSIDX.sas";*/
%include "AEIDX.sas";
%include "REFRANGE.sas";
%include "QS37.sas";
%include "QS40.sas";
%include "QS41.sas";
%include "QS33.sas";
%include "LBCHEM.sas";
%include "LBCHEM25.sas";
%include "LBRANGE.sas";
%include "EX43.sas";

